/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: M03rNrSmXMWV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLinkedinIcon.module.css"; // plasmic-import: M03rNrSmXMWV/css

import Linkedin161SvgrepoCom2SvgIcon from "./icons/PlasmicIcon__Linkedin161SvgrepoCom2Svg"; // plasmic-import: AIRz8ScytNC6/icon

createPlasmicElementProxy;

export type PlasmicLinkedinIcon__VariantMembers = {};
export type PlasmicLinkedinIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicLinkedinIcon__VariantsArgs;
export const PlasmicLinkedinIcon__VariantProps = new Array<VariantPropType>();

export type PlasmicLinkedinIcon__ArgsType = {};
type ArgPropType = keyof PlasmicLinkedinIcon__ArgsType;
export const PlasmicLinkedinIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicLinkedinIcon__OverridesType = {
  social?: Flex__<"a"> & Partial<LinkProps>;
  wrapper?: Flex__<"div">;
  icon?: Flex__<"svg">;
};

export interface DefaultLinkedinIconProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLinkedinIcon__RenderFunc(props: {
  variants: PlasmicLinkedinIcon__VariantsArgs;
  args: PlasmicLinkedinIcon__ArgsType;
  overrides: PlasmicLinkedinIcon__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <PlasmicLink__
      data-plasmic-name={"social"}
      data-plasmic-override={overrides.social}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "a",
        "a__uyaK1",
        "root_reset_uyaK17nhz8WhGjYZfKjMhX",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.social
      )}
      component={Link}
      legacyBehavior={false}
      onClick={async event => {
        const $steps = {};

        $steps["updateStateVariable"] = true
          ? (() => {
              const actionArgs = {};
              return (({ variable, value, startIndex, deleteCount }) => {
                if (!variable) {
                  return;
                }
                const { objRoot, variablePath } = variable;
                undefined;
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["updateStateVariable"] != null &&
          typeof $steps["updateStateVariable"] === "object" &&
          typeof $steps["updateStateVariable"].then === "function"
        ) {
          $steps["updateStateVariable"] = await $steps["updateStateVariable"];
        }
      }}
      platform={"nextjs"}
    >
      <div
        data-plasmic-name={"wrapper"}
        data-plasmic-override={overrides.wrapper}
        className={classNames("all", sty.wrapper)}
      >
        <Linkedin161SvgrepoCom2SvgIcon
          data-plasmic-name={"icon"}
          data-plasmic-override={overrides.icon}
          className={classNames("all", sty.icon)}
          role={"img"}
        />
      </div>
    </PlasmicLink__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  social: ["social", "wrapper", "icon"],
  wrapper: ["wrapper", "icon"],
  icon: ["icon"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  social: "a";
  wrapper: "div";
  icon: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLinkedinIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLinkedinIcon__VariantsArgs;
    args?: PlasmicLinkedinIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLinkedinIcon__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLinkedinIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLinkedinIcon__ArgProps,
          internalVariantPropNames: PlasmicLinkedinIcon__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLinkedinIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "social") {
    func.displayName = "PlasmicLinkedinIcon";
  } else {
    func.displayName = `PlasmicLinkedinIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicLinkedinIcon = Object.assign(
  // Top-level PlasmicLinkedinIcon renders the root element
  makeNodeComponent("social"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    icon: makeNodeComponent("icon"),

    // Metadata about props expected for PlasmicLinkedinIcon
    internalVariantProps: PlasmicLinkedinIcon__VariantProps,
    internalArgProps: PlasmicLinkedinIcon__ArgProps
  }
);

export default PlasmicLinkedinIcon;
/* prettier-ignore-end */
