/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: 5hAHrj7TAU1C

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useMutablePlasmicQueryData } from "@plasmicapp/query";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";
import { usePlasmicQueries } from "@plasmicapp/react-web/lib/data-sources";
import type {
  PlasmicQuery,
  PlasmicQueryResult
} from "@plasmicapp/react-web/lib/data-sources";
import type { QueryComponentNode } from "@plasmicapp/react-web/lib/data-sources";

import Header from "../../Header"; // plasmic-import: qmNXHiKWCTTQ/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import PrimaryBtn from "../../PrimaryBtn"; // plasmic-import: TiffCyYLfuDQ/component
import SecondaryBtn from "../../SecondaryBtn"; // plasmic-import: r3QPz6kMc0wE/component
import Reviews from "../../Reviews"; // plasmic-import: QjfQfEfd1CGs/component
import CtaBottom from "../../CtaBottom"; // plasmic-import: UmfSTsW6wMCz/component
import Footer from "../../Footer"; // plasmic-import: RbMtVh1ii_PZ/component
import FooterLinks from "../../FooterLinks"; // plasmic-import: oZjw7jibmivD/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHome.module.css"; // plasmic-import: 5hAHrj7TAU1C/css

import { fetchGraphQL as __fn_fetchGraphQL } from "@plasmicpkgs/graphql";

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  homepage?: Flex__<"div">;
  pageContainer?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  homeHero?: Flex__<"div">;
  title?: Flex__<"div">;
  h1?: Flex__<"h1">;
  homeBody?: Flex__<"div">;
  intro?: Flex__<"div">;
  text3?: Flex__<"div">;
  title2?: Flex__<"div">;
  section?: Flex__<"div">;
  section2?: Flex__<"div">;
  bakerysolutions?: Flex__<"div">;
  image?: Flex__<"div">;
  text?: Flex__<"div">;
  section3?: Flex__<"div">;
  foodServiceAndRetailPartners?: Flex__<"div">;
  text2?: Flex__<"div">;
  image2?: Flex__<"div">;
  innovationResponsive?: Flex__<"div">;
  buttons?: Flex__<"div">;
  qualitySafetyLink?: Flex__<"a"> & Partial<LinkProps>;
  reviews?: Flex__<typeof Reviews>;
  ctaBottom?: Flex__<typeof CtaBottom>;
  homeFooter?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
  footerLinks?: Flex__<typeof FooterLinks>;
};

export interface DefaultHomeProps {}

const $$ = {
  fetchGraphQL: __fn_fetchGraphQL
};

export const serverQueryTree: QueryComponentNode = {
  type: "component",
  queries: {
    homePage: {
      id: "fetchGraphQL",
      fn: $$.fetchGraphQL,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = { method: "POST", url: null, request: null };
          __composite["url"] = "https://edit-sterling.dangstaging.org/graphql";
          __composite["request"] = {
            query:
              "query MyQuery {\n  pageBy(pageId: 37) {\n    pageContent {\n      fieldGroupName\n      button {\n        fieldGroupName\n        text\n        url\n      }\n      headlineParent {\n        fieldGroupName\n        headlinechild {\n          fieldGroupName\n          headlinefav\n          headlinenormal\n        }\n      }\n      textArea {\n        fieldGroupName\n        text\n      }\n    }\n  }\n}",
            variables: {}
          };
          return __composite;
        })()
      ]
    }
  },
  propsContext: {},
  stateSpecs: [
    {
      path: "footerLinks.linkPath",
      type: "private",
      variableType: "text",
      initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
    }
  ],
  children: []
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "footerLinks.linkPath",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $stateRef = React.useRef<Record<string, unknown> | null>(null);
  const $q = usePlasmicQueries(serverQueryTree, {
    $ctx,
    $props,
    $state: $stateRef.current
  });

  const globalVariants = _useGlobalVariants();

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $q: $q,
    $refs
  });
  $stateRef.current = $state;

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    test: usePlasmicDataOp(() => {
      return {
        sourceId: "9jcy7uWSctPjPwBiwjaShM",
        opId: "bcc4b2e1-5d14-42ff-be62-ec9a5a62df2c",
        userArgs: {},
        cacheKey: `plasmic.$.bcc4b2e1-5d14-42ff-be62-ec9a5a62df2c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    wpGraph: usePlasmicDataOp(() => {
      return {
        sourceId: "9jcy7uWSctPjPwBiwjaShM",
        opId: "bcc4b2e1-5d14-42ff-be62-ec9a5a62df2c",
        userArgs: {},
        cacheKey: `plasmic.$.bcc4b2e1-5d14-42ff-be62-ec9a5a62df2c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy($q),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"homepage"}
          data-plasmic-override={overrides.homepage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uyaK17nhz8WhGjYZfKjMhX",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.homepage,
            ""
          )}
        >
          <div
            data-plasmic-name={"pageContainer"}
            data-plasmic-override={overrides.pageContainer}
            className={classNames("all", sty.pageContainer)}
          >
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />

            <div
              data-plasmic-name={"homeHero"}
              data-plasmic-override={overrides.homeHero}
              className={classNames("all", sty.homeHero)}
            >
              <Reveal
                className={classNames("__wab_instance", sty.reveal__qyrRe)}
                triggerOnce={true}
              >
                <div
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  className={classNames("all", sty.title)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      "all",
                      "h1",
                      "h1__uyaK1",
                      "__wab_text",
                      sty.h1,
                      hasVariant(globalVariants, "screen", "desktop")
                        ? "cambria-lineheight"
                        : "cambria-lineheight"
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $q.homePage.data.body.data.pageBy.pageContent
                            .headlineParent[0].headlinechild[0].headlinenormal;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </h1>
                  <div
                    className={classNames(
                      "all",
                      "__wab_text",
                      sty.text___4TbN,
                      "h1-script"
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $q.homePage.data.body.data.pageBy.pageContent
                            .headlineParent[0].headlinechild[0].headlinefav;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "like no other.";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
              </Reveal>
              <div className={classNames("all", sty.freeBox__bc7O)}>
                <div className={classNames("all", sty.freeBox___1IyQi)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ij4Ls)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sterling_and_buena_vista_foods/images/bakedgoodsAvif2.avif",
                      fullWidth: 1154,
                      fullHeight: 740,
                      aspectRatio: undefined
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mAvCu)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sterling_and_buena_vista_foods/images/arrow2Png.png",
                      fullWidth: 128,
                      fullHeight: 261,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"homeBody"}
              data-plasmic-override={overrides.homeBody}
              className={classNames("all", sty.homeBody)}
            >
              <div className={classNames("all", sty.freeBox___9VvCh)}>
                <div
                  data-plasmic-name={"intro"}
                  data-plasmic-override={overrides.intro}
                  className={classNames(
                    "all",
                    sty.intro,
                    hasVariant(globalVariants, "screen", "desktop")
                      ? "cambria-lineheight"
                      : "cambria-lineheight"
                  )}
                >
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal___5Ma6E)}
                    triggerOnce={true}
                  >
                    <div
                      data-plasmic-name={"text3"}
                      data-plasmic-override={overrides.text3}
                      className={classNames("all", sty.text3)}
                    >
                      <div
                        data-plasmic-name={"title2"}
                        data-plasmic-override={overrides.title2}
                        className={classNames("all", sty.title2)}
                      >
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__kyQgx,
                            "h3-script"
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $q.homePage.data.body.data.pageBy
                                  .pageContent.headlineParent[1]
                                  .headlinechild[0].headlinefav;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Custom-crafted";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <h3
                          className={classNames(
                            "all",
                            "h3",
                            "h3__uyaK1",
                            "__wab_text",
                            sty.h3__wdfVl,
                            hasVariant(globalVariants, "screen", "desktop")
                              ? "cambria-lineheight"
                              : "cambria-lineheight"
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $q.homePage.data.body.data.pageBy
                                  .pageContent.headlineParent[1]
                                  .headlinechild[0].headlinenormal;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "baked goods and snack solutions";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </h3>
                      </div>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__uyaK1",
                          "__wab_text",
                          sty.h3___0Sw2Y
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $q.homePage.data.body.data.pageBy
                                .pageContent.headlineParent[1].headlinechild[1]
                                .headlinenormal;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "made to meet the demands of today\u2019s foodservice, retail, and convenience markets.";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </h3>
                    </div>
                  </Reveal>
                  <div className={classNames("all", sty.freeBox__e8GY)}>
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p__w18L
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $q.homePage.data.body.data.pageBy.pageContent
                              .textArea[0].text;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "At Sterling Foods, we combine bakery expertise, innovation, and leading-edge technology to create products that perform.";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </p>
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p__jid1W
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $q.homePage.data.body.data.pageBy.pageContent
                              .textArea[1].text;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </p>
                  </div>
                  <div className={classNames("all", sty.freeBox__v56Y6)}>
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal___2U43Q
                      )}
                      triggerOnce={true}
                    >
                      <PrimaryBtn
                        className={classNames(
                          "__wab_instance",
                          sty.primaryBtn__h8Wfb
                        )}
                      >
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__cEfj0
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $q.homePage.data.body.data.pageBy
                                  .pageContent.button[0].text;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Start Your Project";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </PrimaryBtn>
                    </Reveal>
                    <PlasmicLink__
                      className={classNames(
                        "all",
                        "a",
                        "a__uyaK1",
                        sty.link__mAw3Y
                      )}
                      component={Link}
                      href={`/about-us`}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__c6TRs
                        )}
                        triggerOnce={true}
                      >
                        <PrimaryBtn
                          className={classNames(
                            "__wab_instance",
                            sty.primaryBtn__bH4Ix
                          )}
                        >
                          <div
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.text__ye4QN
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $q.homePage.data.body.data.pageBy
                                    .pageContent.button[1].text;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "Learn More About Sterling Foods";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </PrimaryBtn>
                      </Reveal>
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"section"}
                data-plasmic-override={overrides.section}
                className={classNames("all", sty.section)}
              >
                <div
                  data-plasmic-name={"section2"}
                  data-plasmic-override={overrides.section2}
                  className={classNames("all", sty.section2)}
                >
                  <div
                    data-plasmic-name={"bakerysolutions"}
                    data-plasmic-override={overrides.bakerysolutions}
                    className={classNames("all", sty.bakerysolutions)}
                  >
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal__tTiMo
                      )}
                      triggerOnce={true}
                    >
                      <div
                        data-plasmic-name={"image"}
                        data-plasmic-override={overrides.image}
                        className={classNames("all", sty.image)}
                      />
                    </Reveal>
                    <div
                      data-plasmic-name={"text"}
                      data-plasmic-override={overrides.text}
                      className={classNames("all", sty.text)}
                    >
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__s33Bh,
                          "h4-script"
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $q.homePage.data.body.data.pageBy
                                .pageContent.headlineParent[2].headlinechild[0]
                                .headlinefav;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Bakery Solutions";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </h4>
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4___4Rj2M
                        )}
                      >
                        <React.Fragment>
                          {
                            $q.homePage.data.body.data.pageBy.pageContent
                              .headlineParent[2].headlinechild[0].headlinenormal
                          }
                        </React.Fragment>
                      </h4>
                      <p
                        className={classNames(
                          "all",
                          "p",
                          "p__uyaK1",
                          "__wab_text",
                          sty.p___37Rkd
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $q.homePage.data.body.data.pageBy
                                .pageContent.textArea[2].text;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "We understand that consumer tastes, operational needs, and market demands are always evolving. That\u2019s why we take a flexible, can-do approach to product development, production, and partnership.\nOur team works with you to create bakery solutions that are consistent, scalable, and made with quality and food safety at the forefront.";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </p>
                      <PlasmicLink__
                        className={classNames(
                          "all",
                          "a",
                          "a__uyaK1",
                          sty.link__qNltJ
                        )}
                        component={Link}
                        href={`/capabilities`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        <Reveal
                          className={classNames(
                            "__wab_instance",
                            sty.reveal___8ZBZ
                          )}
                          triggerOnce={true}
                        >
                          <PrimaryBtn
                            className={classNames(
                              "__wab_instance",
                              sty.primaryBtn__sB6Y
                            )}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__tzNq
                              )}
                            >
                              <React.Fragment>
                                {
                                  $q.homePage.data.body.data.pageBy.pageContent
                                    .button[2].text
                                }
                              </React.Fragment>
                            </div>
                          </PrimaryBtn>
                        </Reveal>
                      </PlasmicLink__>
                    </div>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__luhuh)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      hasVariant(globalVariants, "screen", "desktop")
                        ? {
                            src: "/plasmic/sterling_and_buena_vista_foods/images/arrow4Png.png",
                            fullWidth: 147,
                            fullHeight: 237,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/sterling_and_buena_vista_foods/images/vector2Svg.svg",
                            fullWidth: 123,
                            fullHeight: 258,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <div
                  data-plasmic-name={"section3"}
                  data-plasmic-override={overrides.section3}
                  className={classNames("all", sty.section3)}
                >
                  <div
                    data-plasmic-name={"foodServiceAndRetailPartners"}
                    data-plasmic-override={
                      overrides.foodServiceAndRetailPartners
                    }
                    className={classNames(
                      "all",
                      sty.foodServiceAndRetailPartners
                    )}
                  >
                    <div
                      data-plasmic-name={"text2"}
                      data-plasmic-override={overrides.text2}
                      className={classNames("all", sty.text2)}
                    >
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__ynMJ,
                          "h4-script"
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $q.homePage.data.body.data.pageBy
                                .pageContent.headlineParent[3].headlinechild[0]
                                .headlinefav;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Serving a Wide Range of";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </h4>
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__lgHx
                        )}
                      >
                        <React.Fragment>
                          {
                            $q.homePage.data.body.data.pageBy.pageContent
                              .headlineParent[3].headlinechild[0].headlinenormal
                          }
                        </React.Fragment>
                      </h4>
                      <p
                        className={classNames(
                          "all",
                          "p",
                          "p__uyaK1",
                          "__wab_text",
                          sty.p__xZzR
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $q.homePage.data.body.data.pageBy
                                .pageContent.textArea[3].text;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Sterling Foods proudly serves:";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </p>
                      <div className={classNames("all", sty.freeBox__tCUx)}>
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__hP5Xl
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  "all",
                                  "ul",
                                  "ul__uyaK1",
                                  sty.ul__wbQ3C
                                )}
                              >
                                <li
                                  className={classNames(
                                    "all",
                                    "li",
                                    "li__uyaK1",
                                    "__wab_text",
                                    sty.li__aVfbp
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $q.homePage.data.body.data.pageBy
                                          .pageContent.textArea[5].text;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                              </ul>
                            }
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  "all",
                                  "ul",
                                  "ul__uyaK1",
                                  sty.ul___45Go2
                                )}
                              >
                                <li
                                  className={classNames(
                                    "all",
                                    "li",
                                    "li__uyaK1",
                                    "__wab_text",
                                    sty.li__yu0Ad
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $q.homePage.data.body.data.pageBy
                                          .pageContent.textArea[6].text;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                              </ul>
                            }
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  "all",
                                  "ul",
                                  "ul__uyaK1",
                                  sty.ul___5A4Y
                                )}
                              >
                                <li
                                  className={classNames(
                                    "all",
                                    "li",
                                    "li__uyaK1",
                                    "__wab_text",
                                    sty.li___4UrCd
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $q.homePage.data.body.data.pageBy
                                          .pageContent.textArea[7].text;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                              </ul>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text___6LhDw
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  "all",
                                  "ul",
                                  "ul__uyaK1",
                                  sty.ul___87S4A
                                )}
                              >
                                <li
                                  className={classNames(
                                    "all",
                                    "li",
                                    "li__uyaK1",
                                    "__wab_text",
                                    sty.li__t9KMp
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $q.homePage.data.body.data.pageBy
                                          .pageContent.textArea[8].text;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                              </ul>
                            }
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  "all",
                                  "ul",
                                  "ul__uyaK1",
                                  sty.ul__y9JOz
                                )}
                              >
                                <li
                                  className={classNames(
                                    "all",
                                    "li",
                                    "li__uyaK1",
                                    "__wab_text",
                                    sty.li__vcYgl
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $q.homePage.data.body.data.pageBy
                                          .pageContent.textArea[9].text;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </li>
                              </ul>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                      <PlasmicLink__
                        className={classNames(
                          "all",
                          "a",
                          "a__uyaK1",
                          sty.link__hcDpt
                        )}
                        component={Link}
                        href={`/markets`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        <Reveal
                          className={classNames(
                            "__wab_instance",
                            sty.reveal__zr2VL
                          )}
                          triggerOnce={true}
                        >
                          <PrimaryBtn
                            className={classNames(
                              "__wab_instance",
                              sty.primaryBtn__gurqP
                            )}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__c0Kxh
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $q.homePage.data.body.data.pageBy
                                      .pageContent.button[3].text;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "View All Markets";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </PrimaryBtn>
                        </Reveal>
                      </PlasmicLink__>
                    </div>
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal__nyOup
                      )}
                      triggerOnce={true}
                    >
                      <div
                        data-plasmic-name={"image2"}
                        data-plasmic-override={overrides.image2}
                        className={classNames("all", sty.image2)}
                      />
                    </Reveal>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"innovationResponsive"}
                data-plasmic-override={overrides.innovationResponsive}
                className={classNames("all", sty.innovationResponsive)}
              >
                <div className={classNames("all", sty.column__dW8Wt)}>
                  <div className={classNames("all", sty.freeBox__r7Arz)} />
                </div>
                <div className={classNames("all", sty.column__f0O4)}>
                  <div className={classNames("all", sty.freeBox__gD3PN)}>
                    <div className={classNames("all", sty.freeBox__cBh8C)}>
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__gwMWe
                        )}
                      >
                        <React.Fragment>
                          {
                            $q.homePage.data.body.data.pageBy.pageContent
                              .headlineParent[4].headlinechild[0].headlinenormal
                          }
                        </React.Fragment>
                      </h4>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__uyaK1",
                          "__wab_text",
                          sty.h3__vQRj1,
                          "h4-script"
                        )}
                      >
                        <React.Fragment>
                          {
                            $q.homePage.data.body.data.pageBy.pageContent
                              .headlineParent[4].headlinechild[0].headlinefav
                          }
                        </React.Fragment>
                      </h3>
                    </div>
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p__pbUxp
                      )}
                    >
                      <React.Fragment>
                        {
                          $q.homePage.data.body.data.pageBy.pageContent
                            .textArea[4].text
                        }
                      </React.Fragment>
                    </p>
                    <div
                      data-plasmic-name={"buttons"}
                      data-plasmic-override={overrides.buttons}
                      className={classNames("all", sty.buttons)}
                    >
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__g7Hro
                        )}
                        triggerOnce={true}
                      >
                        <SecondaryBtn
                          className={classNames(
                            "__wab_instance",
                            sty.secondaryBtn__pKcaL
                          )}
                        >
                          <div
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.text__udAml
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $q.homePage.data.body.data.pageBy
                                    .pageContent.button[4].text;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "View Our Facilities";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </SecondaryBtn>
                      </Reveal>
                      <PlasmicLink__
                        data-plasmic-name={"qualitySafetyLink"}
                        data-plasmic-override={overrides.qualitySafetyLink}
                        className={classNames(
                          "all",
                          "a",
                          "a__uyaK1",
                          sty.qualitySafetyLink
                        )}
                        component={Link}
                        href={`/quality-safety`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        <Reveal
                          className={classNames(
                            "__wab_instance",
                            sty.reveal__fn1Cz
                          )}
                          triggerOnce={true}
                        >
                          <SecondaryBtn
                            className={classNames(
                              "__wab_instance",
                              sty.secondaryBtn__xb607
                            )}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__acejO
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $q.homePage.data.body.data.pageBy
                                      .pageContent.button[5].text;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "Explore Quality & Safety";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </SecondaryBtn>
                        </Reveal>
                      </PlasmicLink__>
                    </div>
                  </div>
                </div>
              </div>
              <Reviews
                data-plasmic-name={"reviews"}
                data-plasmic-override={overrides.reviews}
                className={classNames("__wab_instance", sty.reviews)}
                query={$q.homePage.data}
                wpGraph={$q.homePage.data}
              />

              <CtaBottom
                data-plasmic-name={"ctaBottom"}
                data-plasmic-override={overrides.ctaBottom}
                className={classNames("__wab_instance", sty.ctaBottom)}
                wpGraph={$queries.wpGraph}
              />
            </div>
            <div
              data-plasmic-name={"homeFooter"}
              data-plasmic-override={overrides.homeFooter}
              className={classNames("all", sty.homeFooter)}
            >
              <Footer
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                className={classNames("__wab_instance", sty.footer)}
              />
            </div>
          </div>
          <FooterLinks
            data-plasmic-name={"footerLinks"}
            data-plasmic-override={overrides.footerLinks}
            className={classNames("__wab_instance", sty.footerLinks)}
            linkPath={generateStateValueProp($state, [
              "footerLinks",
              "linkPath"
            ])}
            onLinkPathChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, [
                "footerLinks",
                "linkPath"
              ]).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  homepage: [
    "homepage",
    "pageContainer",
    "header",
    "homeHero",
    "title",
    "h1",
    "homeBody",
    "intro",
    "text3",
    "title2",
    "section",
    "section2",
    "bakerysolutions",
    "image",
    "text",
    "section3",
    "foodServiceAndRetailPartners",
    "text2",
    "image2",
    "innovationResponsive",
    "buttons",
    "qualitySafetyLink",
    "reviews",
    "ctaBottom",
    "homeFooter",
    "footer",
    "footerLinks"
  ],
  pageContainer: [
    "pageContainer",
    "header",
    "homeHero",
    "title",
    "h1",
    "homeBody",
    "intro",
    "text3",
    "title2",
    "section",
    "section2",
    "bakerysolutions",
    "image",
    "text",
    "section3",
    "foodServiceAndRetailPartners",
    "text2",
    "image2",
    "innovationResponsive",
    "buttons",
    "qualitySafetyLink",
    "reviews",
    "ctaBottom",
    "homeFooter",
    "footer"
  ],
  header: ["header"],
  homeHero: ["homeHero", "title", "h1"],
  title: ["title", "h1"],
  h1: ["h1"],
  homeBody: [
    "homeBody",
    "intro",
    "text3",
    "title2",
    "section",
    "section2",
    "bakerysolutions",
    "image",
    "text",
    "section3",
    "foodServiceAndRetailPartners",
    "text2",
    "image2",
    "innovationResponsive",
    "buttons",
    "qualitySafetyLink",
    "reviews",
    "ctaBottom"
  ],
  intro: ["intro", "text3", "title2"],
  text3: ["text3", "title2"],
  title2: ["title2"],
  section: [
    "section",
    "section2",
    "bakerysolutions",
    "image",
    "text",
    "section3",
    "foodServiceAndRetailPartners",
    "text2",
    "image2"
  ],
  section2: ["section2", "bakerysolutions", "image", "text"],
  bakerysolutions: ["bakerysolutions", "image", "text"],
  image: ["image"],
  text: ["text"],
  section3: ["section3", "foodServiceAndRetailPartners", "text2", "image2"],
  foodServiceAndRetailPartners: [
    "foodServiceAndRetailPartners",
    "text2",
    "image2"
  ],
  text2: ["text2"],
  image2: ["image2"],
  innovationResponsive: [
    "innovationResponsive",
    "buttons",
    "qualitySafetyLink"
  ],
  buttons: ["buttons", "qualitySafetyLink"],
  qualitySafetyLink: ["qualitySafetyLink"],
  reviews: ["reviews"],
  ctaBottom: ["ctaBottom"],
  homeFooter: ["homeFooter", "footer"],
  footer: ["footer"],
  footerLinks: ["footerLinks"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  homepage: "div";
  pageContainer: "div";
  header: typeof Header;
  homeHero: "div";
  title: "div";
  h1: "h1";
  homeBody: "div";
  intro: "div";
  text3: "div";
  title2: "div";
  section: "div";
  section2: "div";
  bakerysolutions: "div";
  image: "div";
  text: "div";
  section3: "div";
  foodServiceAndRetailPartners: "div";
  text2: "div";
  image2: "div";
  innovationResponsive: "div";
  buttons: "div";
  qualitySafetyLink: "a";
  reviews: typeof Reviews;
  ctaBottom: typeof CtaBottom;
  homeFooter: "div";
  footer: typeof Footer;
  footerLinks: typeof FooterLinks;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHome__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "homepage") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("homepage"),
  {
    // Helper components rendering sub-elements
    pageContainer: makeNodeComponent("pageContainer"),
    header: makeNodeComponent("header"),
    homeHero: makeNodeComponent("homeHero"),
    title: makeNodeComponent("title"),
    h1: makeNodeComponent("h1"),
    homeBody: makeNodeComponent("homeBody"),
    intro: makeNodeComponent("intro"),
    text3: makeNodeComponent("text3"),
    title2: makeNodeComponent("title2"),
    section: makeNodeComponent("section"),
    section2: makeNodeComponent("section2"),
    bakerysolutions: makeNodeComponent("bakerysolutions"),
    image: makeNodeComponent("image"),
    text: makeNodeComponent("text"),
    section3: makeNodeComponent("section3"),
    foodServiceAndRetailPartners: makeNodeComponent(
      "foodServiceAndRetailPartners"
    ),
    text2: makeNodeComponent("text2"),
    image2: makeNodeComponent("image2"),
    innovationResponsive: makeNodeComponent("innovationResponsive"),
    buttons: makeNodeComponent("buttons"),
    qualitySafetyLink: makeNodeComponent("qualitySafetyLink"),
    reviews: makeNodeComponent("reviews"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    homeFooter: makeNodeComponent("homeFooter"),
    footer: makeNodeComponent("footer"),
    footerLinks: makeNodeComponent("footerLinks"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
