/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: gGkWrZU4DY6g

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import TopMenuLinks from "../../TopMenuLinks"; // plasmic-import: VjQboKjcXrTl/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicIsopenNav.module.css"; // plasmic-import: gGkWrZU4DY6g/css

import Linkedin161SvgrepoCom2SvgIcon from "./icons/PlasmicIcon__Linkedin161SvgrepoCom2Svg"; // plasmic-import: AIRz8ScytNC6/icon

createPlasmicElementProxy;

export type PlasmicIsopenNav__VariantMembers = {
  animateImage: "animateImage";
};
export type PlasmicIsopenNav__VariantsArgs = {
  animateImage?: SingleBooleanChoiceArg<"animateImage">;
};
type VariantPropType = keyof PlasmicIsopenNav__VariantsArgs;
export const PlasmicIsopenNav__VariantProps = new Array<VariantPropType>(
  "animateImage"
);

export type PlasmicIsopenNav__ArgsType = {};
type ArgPropType = keyof PlasmicIsopenNav__ArgsType;
export const PlasmicIsopenNav__ArgProps = new Array<ArgPropType>();

export type PlasmicIsopenNav__OverridesType = {
  isopenNav?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  _1?: Flex__<"a"> & Partial<LinkProps>;
  _8?: Flex__<"a"> & Partial<LinkProps>;
  _9?: Flex__<"a"> & Partial<LinkProps>;
  _10?: Flex__<"a"> & Partial<LinkProps>;
  _11?: Flex__<"a"> & Partial<LinkProps>;
  _12?: Flex__<"a"> & Partial<LinkProps>;
  _13?: Flex__<"a"> & Partial<LinkProps>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  svg?: Flex__<"svg">;
};

export interface DefaultIsopenNavProps {
  animateImage?: SingleBooleanChoiceArg<"animateImage">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicIsopenNav__RenderFunc(props: {
  variants: PlasmicIsopenNav__VariantsArgs;
  args: PlasmicIsopenNav__ArgsType;
  overrides: PlasmicIsopenNav__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "hoverImage",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $queries.headerComponent.data.response.data.component
                .components.image.node.mediaItemUrl;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "isHovering",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "animateImage",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.animateImage
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $q: {},
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    headerComponent: usePlasmicDataOp(() => {
      return {
        sourceId: "9jcy7uWSctPjPwBiwjaShM",
        opId: "cc4bb718-fb14-439a-91d9-ba3b468facbb",
        userArgs: {},
        cacheKey: `plasmic.$.cc4bb718-fb14-439a-91d9-ba3b468facbb.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"isopenNav"}
      data-plasmic-override={overrides.isopenNav}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uyaK17nhz8WhGjYZfKjMhX",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.isopenNav,
        {
          [sty.isopenNavanimateImage]: hasVariant(
            $state,
            "animateImage",
            "animateImage"
          )
        }
      )}
    >
      <div
        className={classNames("all", sty.freeBox__n5Xy, {
          [sty.freeBoxanimateImage__n5XySrhyo]: hasVariant(
            $state,
            "animateImage",
            "animateImage"
          )
        })}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img, {
            [sty.imganimateImage]: hasVariant(
              $state,
              "animateImage",
              "animateImage"
            )
          })}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"710px"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={
            hasVariant(globalVariants, "screen", "smallTablet")
              ? "350px"
              : "auto"
          }
          loading={"lazy"}
          src={(() => {
            try {
              return $state.hoverImage;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return {
                  src: "/plasmic/sterling_and_buena_vista_foods/images/applepiePng.png",
                  fullWidth: 700,
                  fullHeight: 483,
                  aspectRatio: undefined
                };
              }
              throw e;
            }
          })()}
        />
      </div>
      <div className={classNames("all", sty.freeBox__cek1N)}>
        <div
          className={classNames("all", sty.freeBox__mc2Vk, {
            [sty.freeBoxanimateImage__mc2VkSrhyo]: hasVariant(
              $state,
              "animateImage",
              "animateImage"
            )
          })}
        >
          <PlasmicLink__
            data-plasmic-name={"_1"}
            data-plasmic-override={overrides._1}
            className={classNames("all", "a", "a__uyaK1", sty._1, {
              [sty._1animateImage]: hasVariant(
                $state,
                "animateImage",
                "animateImage"
              )
            })}
            component={Link}
            href={`/about-us`}
            legacyBehavior={false}
            onMouseEnter={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.menu[0].image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 4,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      $stateSet($state, vgroup, true);
                      return true;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            onMouseLeave={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 6,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      $stateSet($state, vgroup, false);
                      return false;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            platform={"nextjs"}
          >
            <TopMenuLinks
              className={classNames("__wab_instance", sty.topMenuLinks___6LOgu)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__qSUz)}
                onMouseEnter={async event => {
                  const $steps = {};

                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] =
                      await $steps["updateStateVariable"];
                  }
                }}
              >
                <React.Fragment>
                  {
                    $queries.headerComponent.data.response.data.component
                      .components.menu[0].menuitem
                  }
                </React.Fragment>
              </div>
            </TopMenuLinks>
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"_8"}
            data-plasmic-override={overrides._8}
            className={classNames("all", "a", "a__uyaK1", sty._8)}
            component={Link}
            href={`/capabilities`}
            legacyBehavior={false}
            onMouseEnter={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.menu[1].image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 2,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      const oldValue = $stateGet($state, vgroup);
                      $stateSet($state, vgroup, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            onMouseLeave={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }
            }}
            platform={"nextjs"}
          >
            <TopMenuLinks
              className={classNames("__wab_instance", sty.topMenuLinks___6QpM)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__jFzyE)}
                onMouseEnter={async event => {
                  const $steps = {};

                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] =
                      await $steps["updateStateVariable"];
                  }
                }}
              >
                <React.Fragment>
                  {
                    $queries.headerComponent.data.response.data.component
                      .components.menu[1].menuitem
                  }
                </React.Fragment>
              </div>
            </TopMenuLinks>
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"_9"}
            data-plasmic-override={overrides._9}
            className={classNames("all", "a", "a__uyaK1", sty._9)}
            component={Link}
            href={`/markets`}
            legacyBehavior={false}
            onMouseEnter={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.menu[2].image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 2,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      const oldValue = $stateGet($state, vgroup);
                      $stateSet($state, vgroup, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            onMouseLeave={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }
            }}
            platform={"nextjs"}
          >
            <TopMenuLinks
              className={classNames("__wab_instance", sty.topMenuLinks__gyBem)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__dDoV)}
                onMouseEnter={async event => {
                  const $steps = {};

                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] =
                      await $steps["updateStateVariable"];
                  }
                }}
              >
                <React.Fragment>
                  {
                    $queries.headerComponent.data.response.data.component
                      .components.menu[2].menuitem
                  }
                </React.Fragment>
              </div>
            </TopMenuLinks>
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"_10"}
            data-plasmic-override={overrides._10}
            className={classNames("all", "a", "a__uyaK1", sty._10)}
            component={Link}
            href={`/our-facilities`}
            legacyBehavior={false}
            onMouseEnter={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.menu[3].image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 2,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      const oldValue = $stateGet($state, vgroup);
                      $stateSet($state, vgroup, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            onMouseLeave={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }
            }}
            platform={"nextjs"}
          >
            <TopMenuLinks
              className={classNames("__wab_instance", sty.topMenuLinks__dtk3O)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__ijm3M)}
                onMouseEnter={async event => {
                  const $steps = {};

                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] =
                      await $steps["updateStateVariable"];
                  }
                }}
              >
                <React.Fragment>
                  {
                    $queries.headerComponent.data.response.data.component
                      .components.menu[3].menuitem
                  }
                </React.Fragment>
              </div>
            </TopMenuLinks>
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"_11"}
            data-plasmic-override={overrides._11}
            className={classNames("all", "a", "a__uyaK1", sty._11, {
              [sty._11animateImage]: hasVariant(
                $state,
                "animateImage",
                "animateImage"
              )
            })}
            component={Link}
            href={`/quality-safety`}
            legacyBehavior={false}
            onMouseEnter={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 2,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      const oldValue = $stateGet($state, vgroup);
                      $stateSet($state, vgroup, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            onMouseLeave={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }
            }}
            platform={"nextjs"}
          >
            <TopMenuLinks
              className={classNames("__wab_instance", sty.topMenuLinks__qr6Sb)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__jGzCe)}
                onMouseEnter={async event => {
                  const $steps = {};

                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] =
                      await $steps["updateStateVariable"];
                  }
                }}
              >
                <React.Fragment>
                  {
                    $queries.headerComponent.data.response.data.component
                      .components.menu[4].menuitem
                  }
                </React.Fragment>
              </div>
            </TopMenuLinks>
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"_12"}
            data-plasmic-override={overrides._12}
            className={classNames("all", "a", "a__uyaK1", sty._12)}
            component={Link}
            href={`/careers`}
            legacyBehavior={false}
            onMouseEnter={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 2,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      const oldValue = $stateGet($state, vgroup);
                      $stateSet($state, vgroup, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            onMouseLeave={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }
            }}
            platform={"nextjs"}
          >
            <TopMenuLinks
              className={classNames("__wab_instance", sty.topMenuLinks__pw0VN)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text___9V80F)}
                onMouseEnter={async event => {
                  const $steps = {};

                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] =
                      await $steps["updateStateVariable"];
                  }
                }}
              >
                <React.Fragment>
                  {
                    $queries.headerComponent.data.response.data.component
                      .components.menu[5].menuitem
                  }
                </React.Fragment>
              </div>
            </TopMenuLinks>
          </PlasmicLink__>
          <PlasmicLink__
            data-plasmic-name={"_13"}
            data-plasmic-override={overrides._13}
            className={classNames("all", "a", "a__uyaK1", sty._13)}
            component={Link}
            href={`/contact-us`}
            legacyBehavior={false}
            onMouseEnter={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }

              $steps["updateHoverImage2"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "animateImage",
                      operation: 2,
                      value: "animateImage"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      const oldValue = $stateGet($state, vgroup);
                      $stateSet($state, vgroup, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage2"] != null &&
                typeof $steps["updateHoverImage2"] === "object" &&
                typeof $steps["updateHoverImage2"].then === "function"
              ) {
                $steps["updateHoverImage2"] = await $steps["updateHoverImage2"];
              }
            }}
            onMouseLeave={async event => {
              const $steps = {};

              $steps["updateHoverImage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["hoverImage"]
                      },
                      operation: 0,
                      value:
                        $queries.headerComponent.data.response.data.component
                          .components.image.node.mediaItemUrl
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateHoverImage"] != null &&
                typeof $steps["updateHoverImage"] === "object" &&
                typeof $steps["updateHoverImage"].then === "function"
              ) {
                $steps["updateHoverImage"] = await $steps["updateHoverImage"];
              }
            }}
            platform={"nextjs"}
          >
            <TopMenuLinks
              className={classNames("__wab_instance", sty.topMenuLinks__yEuy4)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__n7Zkf)}
                onMouseEnter={async event => {
                  const $steps = {};

                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] =
                      await $steps["updateStateVariable"];
                  }
                }}
              >
                <React.Fragment>
                  {
                    $queries.headerComponent.data.response.data.component
                      .components.menu[6].menuitem
                  }
                </React.Fragment>
              </div>
            </TopMenuLinks>
          </PlasmicLink__>
        </div>
        <div
          className={classNames("all", sty.freeBox__wqMwo, {
            [sty.freeBoxanimateImage__wqMwoSrhyo]: hasVariant(
              $state,
              "animateImage",
              "animateImage"
            )
          })}
        >
          <PlasmicLink__
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames("all", "a", "a__uyaK1", sty.link, {
              [sty.linkanimateImage]: hasVariant(
                $state,
                "animateImage",
                "animateImage"
              )
            })}
            component={Link}
            href={
              $queries.headerComponent.data.response.data.component.components
                .socialMedia[2].urlSocial
            }
            legacyBehavior={false}
            platform={"nextjs"}
            target={
              hasVariant($state, "animateImage", "animateImage")
                ? "_blank"
                : undefined
            }
          >
            <Linkedin161SvgrepoCom2SvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames("all", sty.svg, {
                [sty.svganimateImage]: hasVariant(
                  $state,
                  "animateImage",
                  "animateImage"
                )
              })}
              role={"img"}
            />
          </PlasmicLink__>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  isopenNav: [
    "isopenNav",
    "img",
    "_1",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "_13",
    "link",
    "svg"
  ],
  img: ["img"],
  _1: ["_1"],
  _8: ["_8"],
  _9: ["_9"],
  _10: ["_10"],
  _11: ["_11"],
  _12: ["_12"],
  _13: ["_13"],
  link: ["link", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  isopenNav: "div";
  img: typeof PlasmicImg__;
  _1: "a";
  _8: "a";
  _9: "a";
  _10: "a";
  _11: "a";
  _12: "a";
  _13: "a";
  link: "a";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicIsopenNav__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicIsopenNav__VariantsArgs;
    args?: PlasmicIsopenNav__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicIsopenNav__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicIsopenNav__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicIsopenNav__ArgProps,
          internalVariantPropNames: PlasmicIsopenNav__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicIsopenNav__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "isopenNav") {
    func.displayName = "PlasmicIsopenNav";
  } else {
    func.displayName = `PlasmicIsopenNav.${nodeName}`;
  }
  return func;
}

export const PlasmicIsopenNav = Object.assign(
  // Top-level PlasmicIsopenNav renders the root element
  makeNodeComponent("isopenNav"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    _1: makeNodeComponent("_1"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    _12: makeNodeComponent("_12"),
    _13: makeNodeComponent("_13"),
    link: makeNodeComponent("link"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicIsopenNav
    internalVariantProps: PlasmicIsopenNav__VariantProps,
    internalArgProps: PlasmicIsopenNav__ArgProps
  }
);

export default PlasmicIsopenNav;
/* prettier-ignore-end */
