/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: r3QPz6kMc0wE

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicSecondaryBtn.module.css"; // plasmic-import: r3QPz6kMc0wE/css

createPlasmicElementProxy;

export type PlasmicSecondaryBtn__VariantMembers = {};
export type PlasmicSecondaryBtn__VariantsArgs = {};
type VariantPropType = keyof PlasmicSecondaryBtn__VariantsArgs;
export const PlasmicSecondaryBtn__VariantProps = new Array<VariantPropType>();

export type PlasmicSecondaryBtn__ArgsType = { children?: React.ReactNode };
type ArgPropType = keyof PlasmicSecondaryBtn__ArgsType;
export const PlasmicSecondaryBtn__ArgProps = new Array<ArgPropType>("children");

export type PlasmicSecondaryBtn__OverridesType = {
  secondaryBtn?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultSecondaryBtnProps {
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSecondaryBtn__RenderFunc(props: {
  variants: PlasmicSecondaryBtn__VariantsArgs;
  args: PlasmicSecondaryBtn__ArgsType;
  overrides: PlasmicSecondaryBtn__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const [isSecondaryBtnActive, triggerSecondaryBtnActiveProps] = useTrigger(
    "usePressed",
    {}
  );
  const triggers = {
    active_secondaryBtn: isSecondaryBtnActive
  };

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"secondaryBtn"}
      data-plasmic-override={overrides.secondaryBtn}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uyaK17nhz8WhGjYZfKjMhX",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.secondaryBtn
      )}
      data-plasmic-trigger-props={[triggerSecondaryBtnActiveProps]}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        {renderPlasmicSlot({
          defaultContents: "Label",
          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  secondaryBtn: ["secondaryBtn", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  secondaryBtn: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSecondaryBtn__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSecondaryBtn__VariantsArgs;
    args?: PlasmicSecondaryBtn__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSecondaryBtn__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSecondaryBtn__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSecondaryBtn__ArgProps,
          internalVariantPropNames: PlasmicSecondaryBtn__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSecondaryBtn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "secondaryBtn") {
    func.displayName = "PlasmicSecondaryBtn";
  } else {
    func.displayName = `PlasmicSecondaryBtn.${nodeName}`;
  }
  return func;
}

export const PlasmicSecondaryBtn = Object.assign(
  // Top-level PlasmicSecondaryBtn renders the root element
  makeNodeComponent("secondaryBtn"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicSecondaryBtn
    internalVariantProps: PlasmicSecondaryBtn__VariantProps,
    internalArgProps: PlasmicSecondaryBtn__ArgProps
  }
);

export default PlasmicSecondaryBtn;
/* prettier-ignore-end */
