/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX

import {
  createUseStyleTokens,
  createStyleTokensProvider
} from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule

const data = {
  base: `${"plasmic_tokens_uyaK17nhz8WhGjYZfKjMhX"} ${"plasmic_tokens_5ZtnypMovRHeeP3YTdPCYL"} ${"plasmic_tokens_4vjRXvnb4XuY6J15w9oRcQ"} ${"plasmic_tokens_ohDidvG9XsCeFumugENU3J"} ${"plasmic_tokens_jkU633o1Cz7HrJdwdxhVHk"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  {
    base: `${"plasmic_tokens_override_uyaK17nhz8WhGjYZfKjMhX"} ${data.base}`,
    varianted: data.varianted
  },
  _useGlobalVariants
);
