/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: SLasZNIBO9mF

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicReviewBox.module.css"; // plasmic-import: SLasZNIBO9mF/css

import Frame42Icon from "./icons/PlasmicIcon__Frame42"; // plasmic-import: fvdJKJiExZAu/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: B-rs-DifXAgf/icon

createPlasmicElementProxy;

export type PlasmicReviewBox__VariantMembers = {};
export type PlasmicReviewBox__VariantsArgs = {};
type VariantPropType = keyof PlasmicReviewBox__VariantsArgs;
export const PlasmicReviewBox__VariantProps = new Array<VariantPropType>();

export type PlasmicReviewBox__ArgsType = {};
type ArgPropType = keyof PlasmicReviewBox__ArgsType;
export const PlasmicReviewBox__ArgProps = new Array<ArgPropType>();

export type PlasmicReviewBox__OverridesType = {
  frame48?: Flex__<"div">;
  frame49?: Flex__<"div">;
  frame50?: Flex__<"div">;
  text?: Flex__<"div">;
  frame51?: Flex__<"div">;
};

export interface DefaultReviewBoxProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicReviewBox__RenderFunc(props: {
  variants: PlasmicReviewBox__VariantsArgs;
  args: PlasmicReviewBox__ArgsType;
  overrides: PlasmicReviewBox__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"frame48"}
      data-plasmic-override={overrides.frame48}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uyaK17nhz8WhGjYZfKjMhX",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.frame48
      )}
    >
      <div
        data-plasmic-name={"frame49"}
        data-plasmic-override={overrides.frame49}
        className={classNames("all", sty.frame49)}
      >
        <Frame42Icon
          className={classNames("all", sty.svg__qrsbe)}
          role={"img"}
        />
      </div>
      <div
        data-plasmic-name={"frame50"}
        data-plasmic-override={overrides.frame50}
        className={classNames("all", sty.frame50)}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames("all", "__wab_text", sty.text)}
        >
          <React.Fragment>
            <React.Fragment>
              {
                "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n\n\n"
              }
            </React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__uyaK1"
              }
              style={{ fontWeight: 700 }}
            >
              {"JOHN DOE"}
            </span>
          </React.Fragment>
        </div>
      </div>
      <div
        data-plasmic-name={"frame51"}
        data-plasmic-override={overrides.frame51}
        className={classNames("all", sty.frame51)}
      >
        <Group2Icon
          className={classNames("all", sty.svg__nHpXo)}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame48: ["frame48", "frame49", "frame50", "text", "frame51"],
  frame49: ["frame49"],
  frame50: ["frame50", "text"],
  text: ["text"],
  frame51: ["frame51"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  frame48: "div";
  frame49: "div";
  frame50: "div";
  text: "div";
  frame51: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicReviewBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicReviewBox__VariantsArgs;
    args?: PlasmicReviewBox__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicReviewBox__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicReviewBox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicReviewBox__ArgProps,
          internalVariantPropNames: PlasmicReviewBox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicReviewBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame48") {
    func.displayName = "PlasmicReviewBox";
  } else {
    func.displayName = `PlasmicReviewBox.${nodeName}`;
  }
  return func;
}

export const PlasmicReviewBox = Object.assign(
  // Top-level PlasmicReviewBox renders the root element
  makeNodeComponent("frame48"),
  {
    // Helper components rendering sub-elements
    frame49: makeNodeComponent("frame49"),
    frame50: makeNodeComponent("frame50"),
    text: makeNodeComponent("text"),
    frame51: makeNodeComponent("frame51"),

    // Metadata about props expected for PlasmicReviewBox
    internalVariantProps: PlasmicReviewBox__VariantProps,
    internalArgProps: PlasmicReviewBox__ArgProps
  }
);

export default PlasmicReviewBox;
/* prettier-ignore-end */
