/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: RbMtVh1ii_PZ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import SocialBtns from "../../SocialBtns"; // plasmic-import: 5db6kxlVpzXq/component
import MenuList from "../../MenuList"; // plasmic-import: -6leV5wneOe9/component
import { AntdAccordion } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { accordionHelpers as AntdAccordion_Helpers } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { AntdAccordionItem } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import FooterLinks from "../../FooterLinks"; // plasmic-import: oZjw7jibmivD/component
import DividerLine from "../../DividerLine"; // plasmic-import: 4JeLlkbzO3aD/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicFooter.module.css"; // plasmic-import: RbMtVh1ii_PZ/css

import MapPinFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__MapPinFilled"; // plasmic-import: zXkaTx8ISMNO/icon
import ArrowNarrowUpIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__ArrowNarrowUp"; // plasmic-import: uqJlQ6IPOM_y/icon

createPlasmicElementProxy;

export type PlasmicFooter__VariantMembers = {};
export type PlasmicFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooter__VariantsArgs;
export const PlasmicFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicFooter__ArgsType = { headerDestination?: string };
type ArgPropType = keyof PlasmicFooter__ArgsType;
export const PlasmicFooter__ArgProps = new Array<ArgPropType>(
  "headerDestination"
);

export type PlasmicFooter__OverridesType = {
  footer?: Flex__<"div">;
  parent?: Flex__<"div">;
  topChild?: Flex__<"div">;
  logo?: Flex__<"a"> & Partial<LinkProps>;
  text?: Flex__<"div">;
  socialBtns?: Flex__<typeof SocialBtns>;
  menus?: Flex__<"div">;
  locations3?: Flex__<"div">;
  locations4?: Flex__<"div">;
  address4?: Flex__<"div">;
  address5?: Flex__<"div">;
  address6?: Flex__<"div">;
  accordion?: Flex__<typeof AntdAccordion>;
  locations5?: Flex__<"div">;
  address7?: Flex__<"div">;
  address8?: Flex__<"div">;
  address9?: Flex__<"div">;
  footerMenu?: Flex__<"div">;
  footerLinks?: Flex__<typeof FooterLinks>;
  clientLogin?: Flex__<"div">;
  footerLinks2?: Flex__<typeof FooterLinks>;
  footerLinks3?: Flex__<typeof FooterLinks>;
  clientLogin3?: Flex__<"div">;
  terms?: Flex__<typeof FooterLinks>;
  footerLinks4?: Flex__<typeof FooterLinks>;
  clientLogin5?: Flex__<"div">;
  colorBar?: Flex__<"div">;
};

export interface DefaultFooterProps {
  headerDestination?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooter__RenderFunc(props: {
  variants: PlasmicFooter__VariantsArgs;
  args: PlasmicFooter__ArgsType;
  overrides: PlasmicFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          headerDestination: "#top-header"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "accordion.activePanelId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec(
          "activePanelId",
          AntdAccordion_Helpers
        )
      },
      {
        path: "footerLinks.linkPath",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "footerLinks2.linkPath",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "footerLinks3.linkPath",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "terms.linkPath",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          "/terms-and-conditions"
      },
      {
        path: "footerLinks4.linkPath",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"footer"}
      data-plasmic-override={overrides.footer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uyaK17nhz8WhGjYZfKjMhX",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.footer
      )}
    >
      <div
        data-plasmic-name={"parent"}
        data-plasmic-override={overrides.parent}
        className={classNames("all", sty.parent)}
      >
        <div
          data-plasmic-name={"topChild"}
          data-plasmic-override={overrides.topChild}
          className={classNames("all", sty.topChild)}
        >
          <div className={classNames("all", sty.freeBox__cBvFy)}>
            <PlasmicLink__
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames("all", "a", "a__uyaK1", sty.logo)}
              component={Link}
              href={`/`}
              legacyBehavior={false}
              platform={"nextjs"}
            />

            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames("all", "__wab_text", sty.text)}
            >
              {hasVariant(globalVariants, "screen", "smallTablet")
                ? "From restaurants and non-commercial foodservice to convenience stores and in-store bakeries, we partner\r with our customers to deliver high-quality baked goods\rand snack products tailored to their needs."
                : "From restaurants and non-commercial foodservice to convenience stores and in-store bakeries, we partner\r\nwith our customers to deliver high-quality baked goods\rand snack products tailored to their needs."}
            </div>
            <SocialBtns
              data-plasmic-name={"socialBtns"}
              data-plasmic-override={overrides.socialBtns}
              className={classNames("__wab_instance", sty.socialBtns)}
            />
          </div>
          <div
            data-plasmic-name={"menus"}
            data-plasmic-override={overrides.menus}
            className={classNames("all", sty.menus)}
          >
            <div
              data-plasmic-name={"locations3"}
              data-plasmic-override={overrides.locations3}
              className={classNames("all", sty.locations3)}
            >
              <div className={classNames("all", "__wab_text", sty.text__aJh09)}>
                {hasVariant(globalVariants, "screen", "desktop")
                  ? "Quick Links"
                  : "Quick Links"}
              </div>
              <MenuList
                className={classNames("__wab_instance", sty.menuList__xhVKa)}
              />
            </div>
            <div
              data-plasmic-name={"locations4"}
              data-plasmic-override={overrides.locations4}
              className={classNames("all", sty.locations4)}
            >
              <div className={classNames("all", "__wab_text", sty.text__tZTvp)}>
                {"Locations"}
              </div>
              <div
                data-plasmic-name={"address4"}
                data-plasmic-override={overrides.address4}
                className={classNames("all", sty.address4)}
              >
                <div className={classNames("all", sty.freeBox__nwfJx)}>
                  <MapPinFilledIcon
                    className={classNames("all", sty.svg__mYnG2)}
                    role={"img"}
                  />

                  <div
                    className={classNames("all", "__wab_text", sty.text__sVeea)}
                  >
                    {"San Antonio, Texas (Headquarters)\r"}
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__k3FMk)}
                >
                  {
                    "1075 Arion Parkway\nSan Antonio, TX 78216\r \n210-490-1669\r"
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"address5"}
                data-plasmic-override={overrides.address5}
                className={classNames("all", sty.address5)}
              >
                <div className={classNames("all", sty.freeBox__c8X)}>
                  <MapPinFilledIcon
                    className={classNames("all", sty.svg__qPf4C)}
                    role={"img"}
                  />

                  <div
                    className={classNames("all", "__wab_text", sty.text__m3JKj)}
                  >
                    {"Azusa, California"}
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__joQX)}
                >
                  {
                    "1075 Arion Parkway\nSan Antonio, TX 78216\r\n210-490-1669\r"
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"address6"}
                data-plasmic-override={overrides.address6}
                className={classNames("all", sty.address6)}
              >
                <div className={classNames("all", sty.freeBox__ro2So)}>
                  <MapPinFilledIcon
                    className={classNames("all", sty.svg__kmtS)}
                    role={"img"}
                  />

                  <div
                    className={classNames("all", "__wab_text", sty.text__ygswT)}
                  >
                    {"Union City, California"}
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__sUzzh)}
                >
                  {
                    "Union City, California\n33300 Western Ave\nUnion City CA, 94587\n510-487-2600"
                  }
                </div>
              </div>
            </div>
          </div>
        </div>
        {(() => {
          const child$Props = {
            activeKey: generateStateValueProp($state, [
              "accordion",
              "activePanelId"
            ]),
            bordered: false,
            className: classNames("__wab_instance", sty.accordion),
            collapsible: "header",
            destroyInactivePanel: false,
            disabled: false,
            expandIconPosition: "end",
            ghost: false,
            items: (
              <React.Fragment>
                <AntdAccordionItem
                  className={classNames(
                    "__wab_instance",
                    sty.accordionItem__lv70J
                  )}
                  headerClass={classNames({ [sty["pcls_TybCRrd2lCHE"]]: true })}
                  id={1}
                  label2={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__rvMvW
                      )}
                    >
                      {"Quick Links"}
                    </div>
                  }
                  showArrow={true}
                >
                  <MenuList
                    className={classNames(
                      "__wab_instance",
                      sty.menuList__mw27I
                    )}
                  />
                </AntdAccordionItem>
                <AntdAccordionItem
                  className={classNames(
                    "__wab_instance",
                    sty.accordionItem__mfMxd
                  )}
                  id={2}
                  label2={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text___7LLiJ
                      )}
                    >
                      {"Locations"}
                    </div>
                  }
                  showArrow={true}
                >
                  <div
                    data-plasmic-name={"locations5"}
                    data-plasmic-override={overrides.locations5}
                    className={classNames("all", sty.locations5)}
                  >
                    <div
                      data-plasmic-name={"address7"}
                      data-plasmic-override={overrides.address7}
                      className={classNames("all", sty.address7)}
                    >
                      <div className={classNames("all", sty.freeBox__iWovo)}>
                        <MapPinFilledIcon
                          className={classNames("all", sty.svg__bUpHo)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__fMZz
                          )}
                        >
                          {"San Antonio, Texas (Headquarters)\r"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text___3HMsC
                        )}
                      >
                        {
                          "1075 Arion Parkway\nSan Antonio, TX 78216\r\n210-490-1669\r"
                        }
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"address8"}
                      data-plasmic-override={overrides.address8}
                      className={classNames("all", sty.address8)}
                    >
                      <div className={classNames("all", sty.freeBox__h8Qez)}>
                        <MapPinFilledIcon
                          className={classNames("all", sty.svg__fymkI)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__oiy7U
                          )}
                        >
                          {"Azusa, California"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__l3LSj
                        )}
                      >
                        {
                          "1075 Arion Parkway\nSan Antonio, TX 78216\r\n210-490-1669\r"
                        }
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"address9"}
                      data-plasmic-override={overrides.address9}
                      className={classNames("all", sty.address9)}
                    >
                      <div className={classNames("all", sty.freeBox__iVf3Y)}>
                        <MapPinFilledIcon
                          className={classNames("all", sty.svg__guZxX)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__cdklQ
                          )}
                        >
                          {"Union City, California"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__lowkE
                        )}
                      >
                        {
                          "Union City, California\n33300 Western Ave\nUnion City CA, 94587\n510-487-2600"
                        }
                      </div>
                    </div>
                  </div>
                </AntdAccordionItem>
              </React.Fragment>
            ),
            onChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "activePanelId",
                ["accordion", "activePanelId"],
                AntdAccordion_Helpers
              ).apply(null, eventArgs);
            },
            rotationAngle: 90,
            size: "middle"
          };
          initializeCodeComponentStates(
            $state,
            [
              {
                name: "activePanelId",
                plasmicStateName: "accordion.activePanelId"
              }
            ],
            [],
            AntdAccordion_Helpers ?? {},
            child$Props
          );

          return (
            <AntdAccordion
              data-plasmic-name={"accordion"}
              data-plasmic-override={overrides.accordion}
              {...child$Props}
            />
          );
        })()}
        <div className={classNames("all", sty.freeBox___9KFeZ)}>
          <div
            data-plasmic-name={"footerMenu"}
            data-plasmic-override={overrides.footerMenu}
            className={classNames("all", sty.footerMenu)}
          >
            <FooterLinks
              data-plasmic-name={"footerLinks"}
              data-plasmic-override={overrides.footerLinks}
              className={classNames("__wab_instance", sty.footerLinks)}
              linkPath={generateStateValueProp($state, [
                "footerLinks",
                "linkPath"
              ])}
              onLinkPathChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "footerLinks",
                  "linkPath"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <div
                data-plasmic-name={"clientLogin"}
                data-plasmic-override={overrides.clientLogin}
                className={classNames("all", "__wab_text", sty.clientLogin)}
              >
                {"Client Login"}
              </div>
            </FooterLinks>
            <DividerLine
              className={classNames("__wab_instance", sty.dividerLine___2Km7Z)}
            />

            <FooterLinks
              data-plasmic-name={"footerLinks2"}
              data-plasmic-override={overrides.footerLinks2}
              className={classNames("__wab_instance", sty.footerLinks2)}
              linkPath={generateStateValueProp($state, [
                "footerLinks2",
                "linkPath"
              ])}
              onLinkPathChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "footerLinks2",
                  "linkPath"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <div className={classNames("all", "__wab_text", sty.text__zzEq3)}>
                {"Privacy Policy"}
              </div>
            </FooterLinks>
            <DividerLine
              className={classNames("__wab_instance", sty.dividerLine__hkj9I)}
            />

            <FooterLinks
              data-plasmic-name={"footerLinks3"}
              data-plasmic-override={overrides.footerLinks3}
              className={classNames("__wab_instance", sty.footerLinks3)}
              linkPath={generateStateValueProp($state, [
                "footerLinks3",
                "linkPath"
              ])}
              onLinkPathChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "footerLinks3",
                  "linkPath"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <div
                data-plasmic-name={"clientLogin3"}
                data-plasmic-override={overrides.clientLogin3}
                className={classNames("all", "__wab_text", sty.clientLogin3)}
              >
                {"Disclosure"}
              </div>
            </FooterLinks>
            <DividerLine
              className={classNames("__wab_instance", sty.dividerLine___0Jplz)}
            />

            <PlasmicLink__
              className={classNames("all", "a", "a__uyaK1", sty.link__i6V8B)}
              component={Link}
              href={`/terms-and-conditions`}
              legacyBehavior={false}
              onClick={async event => {
                const $steps = {};

                $steps["updateAccordionActivePanelId"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["accordion", "activePanelId"]
                        },
                        operation: 0
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateAccordionActivePanelId"] != null &&
                  typeof $steps["updateAccordionActivePanelId"] === "object" &&
                  typeof $steps["updateAccordionActivePanelId"].then ===
                    "function"
                ) {
                  $steps["updateAccordionActivePanelId"] =
                    await $steps["updateAccordionActivePanelId"];
                }
              }}
              platform={"nextjs"}
            >
              <FooterLinks
                data-plasmic-name={"terms"}
                data-plasmic-override={overrides.terms}
                className={classNames("__wab_instance", sty.terms)}
                linkPath={generateStateValueProp($state, ["terms", "linkPath"])}
                onLinkPathChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "terms",
                    "linkPath"
                  ]).apply(null, eventArgs);

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__hYKe)}
                >
                  {"Terms of Use"}
                </div>
              </FooterLinks>
            </PlasmicLink__>
            <DividerLine
              className={classNames("__wab_instance", sty.dividerLine__cx0Jy)}
            />

            <FooterLinks
              data-plasmic-name={"footerLinks4"}
              data-plasmic-override={overrides.footerLinks4}
              className={classNames("__wab_instance", sty.footerLinks4)}
              linkPath={generateStateValueProp($state, [
                "footerLinks4",
                "linkPath"
              ])}
              onLinkPathChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "footerLinks4",
                  "linkPath"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <div
                data-plasmic-name={"clientLogin5"}
                data-plasmic-override={overrides.clientLogin5}
                className={classNames("all", "__wab_text", sty.clientLogin5)}
              >
                {"Accessibility"}
              </div>
            </FooterLinks>
          </div>
          <div className={classNames("all", "__wab_text", sty.text__nL8Zp)}>
            {"\u00a9 Sterling Foods, Inc. All Rights Reserved"}
          </div>
        </div>
        <div className={classNames("all", sty.freeBox__cSkrB)}>
          <PlasmicLink__
            className={classNames("all", "a", "a__uyaK1", sty.link___9GYH)}
            component={Link}
            href={args.headerDestination}
            legacyBehavior={false}
            onClick={async event => {
              const $steps = {};

              $steps["goToHeaderTop"] = true
                ? (() => {
                    const actionArgs = { destination: "#header-top" };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToHeaderTop"] != null &&
                typeof $steps["goToHeaderTop"] === "object" &&
                typeof $steps["goToHeaderTop"].then === "function"
              ) {
                $steps["goToHeaderTop"] = await $steps["goToHeaderTop"];
              }
            }}
            platform={"nextjs"}
          >
            <ArrowNarrowUpIcon
              className={classNames("all", sty.svg___9MhDf)}
              role={"img"}
            />
          </PlasmicLink__>
        </div>
      </div>
      <div
        data-plasmic-name={"colorBar"}
        data-plasmic-override={overrides.colorBar}
        className={classNames("all", sty.colorBar)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  footer: [
    "footer",
    "parent",
    "topChild",
    "logo",
    "text",
    "socialBtns",
    "menus",
    "locations3",
    "locations4",
    "address4",
    "address5",
    "address6",
    "accordion",
    "locations5",
    "address7",
    "address8",
    "address9",
    "footerMenu",
    "footerLinks",
    "clientLogin",
    "footerLinks2",
    "footerLinks3",
    "clientLogin3",
    "terms",
    "footerLinks4",
    "clientLogin5",
    "colorBar"
  ],
  parent: [
    "parent",
    "topChild",
    "logo",
    "text",
    "socialBtns",
    "menus",
    "locations3",
    "locations4",
    "address4",
    "address5",
    "address6",
    "accordion",
    "locations5",
    "address7",
    "address8",
    "address9",
    "footerMenu",
    "footerLinks",
    "clientLogin",
    "footerLinks2",
    "footerLinks3",
    "clientLogin3",
    "terms",
    "footerLinks4",
    "clientLogin5"
  ],
  topChild: [
    "topChild",
    "logo",
    "text",
    "socialBtns",
    "menus",
    "locations3",
    "locations4",
    "address4",
    "address5",
    "address6"
  ],
  logo: ["logo"],
  text: ["text"],
  socialBtns: ["socialBtns"],
  menus: [
    "menus",
    "locations3",
    "locations4",
    "address4",
    "address5",
    "address6"
  ],
  locations3: ["locations3"],
  locations4: ["locations4", "address4", "address5", "address6"],
  address4: ["address4"],
  address5: ["address5"],
  address6: ["address6"],
  accordion: ["accordion", "locations5", "address7", "address8", "address9"],
  locations5: ["locations5", "address7", "address8", "address9"],
  address7: ["address7"],
  address8: ["address8"],
  address9: ["address9"],
  footerMenu: [
    "footerMenu",
    "footerLinks",
    "clientLogin",
    "footerLinks2",
    "footerLinks3",
    "clientLogin3",
    "terms",
    "footerLinks4",
    "clientLogin5"
  ],
  footerLinks: ["footerLinks", "clientLogin"],
  clientLogin: ["clientLogin"],
  footerLinks2: ["footerLinks2"],
  footerLinks3: ["footerLinks3", "clientLogin3"],
  clientLogin3: ["clientLogin3"],
  terms: ["terms"],
  footerLinks4: ["footerLinks4", "clientLogin5"],
  clientLogin5: ["clientLogin5"],
  colorBar: ["colorBar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  footer: "div";
  parent: "div";
  topChild: "div";
  logo: "a";
  text: "div";
  socialBtns: typeof SocialBtns;
  menus: "div";
  locations3: "div";
  locations4: "div";
  address4: "div";
  address5: "div";
  address6: "div";
  accordion: typeof AntdAccordion;
  locations5: "div";
  address7: "div";
  address8: "div";
  address9: "div";
  footerMenu: "div";
  footerLinks: typeof FooterLinks;
  clientLogin: "div";
  footerLinks2: typeof FooterLinks;
  footerLinks3: typeof FooterLinks;
  clientLogin3: "div";
  terms: typeof FooterLinks;
  footerLinks4: typeof FooterLinks;
  clientLogin5: "div";
  colorBar: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooter__VariantsArgs;
    args?: PlasmicFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFooter__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooter__ArgProps,
          internalVariantPropNames: PlasmicFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "footer") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("footer"),
  {
    // Helper components rendering sub-elements
    parent: makeNodeComponent("parent"),
    topChild: makeNodeComponent("topChild"),
    logo: makeNodeComponent("logo"),
    text: makeNodeComponent("text"),
    socialBtns: makeNodeComponent("socialBtns"),
    menus: makeNodeComponent("menus"),
    locations3: makeNodeComponent("locations3"),
    locations4: makeNodeComponent("locations4"),
    address4: makeNodeComponent("address4"),
    address5: makeNodeComponent("address5"),
    address6: makeNodeComponent("address6"),
    accordion: makeNodeComponent("accordion"),
    locations5: makeNodeComponent("locations5"),
    address7: makeNodeComponent("address7"),
    address8: makeNodeComponent("address8"),
    address9: makeNodeComponent("address9"),
    footerMenu: makeNodeComponent("footerMenu"),
    footerLinks: makeNodeComponent("footerLinks"),
    clientLogin: makeNodeComponent("clientLogin"),
    footerLinks2: makeNodeComponent("footerLinks2"),
    footerLinks3: makeNodeComponent("footerLinks3"),
    clientLogin3: makeNodeComponent("clientLogin3"),
    terms: makeNodeComponent("terms"),
    footerLinks4: makeNodeComponent("footerLinks4"),
    clientLogin5: makeNodeComponent("clientLogin5"),
    colorBar: makeNodeComponent("colorBar"),

    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
