/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: E0oqoOVOXwfb

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useMutablePlasmicQueryData } from "@plasmicapp/query";

import { usePlasmicQueries } from "@plasmicapp/react-web/lib/data-sources";
import type {
  PlasmicQuery,
  PlasmicQueryResult
} from "@plasmicapp/react-web/lib/data-sources";
import type { QueryComponentNode } from "@plasmicapp/react-web/lib/data-sources";

import Header from "../../Header"; // plasmic-import: qmNXHiKWCTTQ/component
import TopHero from "../../TopHero"; // plasmic-import: 2xRY6WOypZh7/component
import PrimaryBtn from "../../PrimaryBtn"; // plasmic-import: TiffCyYLfuDQ/component
import CtaBottom from "../../CtaBottom"; // plasmic-import: UmfSTsW6wMCz/component
import Footer from "../../Footer"; // plasmic-import: RbMtVh1ii_PZ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicInnovation.module.css"; // plasmic-import: E0oqoOVOXwfb/css

import { fetchGraphQL as __fn_fetchGraphQL } from "@plasmicpkgs/graphql";

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicInnovation__VariantMembers = {};
export type PlasmicInnovation__VariantsArgs = {};
type VariantPropType = keyof PlasmicInnovation__VariantsArgs;
export const PlasmicInnovation__VariantProps = new Array<VariantPropType>();

export type PlasmicInnovation__ArgsType = {};
type ArgPropType = keyof PlasmicInnovation__ArgsType;
export const PlasmicInnovation__ArgProps = new Array<ArgPropType>();

export type PlasmicInnovation__OverridesType = {
  root?: Flex__<"div">;
  pageContainer?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  topHero?: Flex__<typeof TopHero>;
  innovationBody?: Flex__<"div">;
  intro?: Flex__<"div">;
  foodSafety?: Flex__<"div">;
  text?: Flex__<"div">;
  title?: Flex__<"div">;
  paragraph?: Flex__<"div">;
  schoolFoodservice?: Flex__<"div">;
  text2?: Flex__<"div">;
  title2?: Flex__<"div">;
  paragraph2?: Flex__<"div">;
  aboutUs?: Flex__<"a"> & Partial<LinkProps>;
  primaryBtn?: Flex__<typeof PrimaryBtn>;
  convenienceStores?: Flex__<"div">;
  text3?: Flex__<"div">;
  title3?: Flex__<"div">;
  paragraph3?: Flex__<"div">;
  innovationSection?: Flex__<"div">;
  intro2?: Flex__<"div">;
  foodSafety2?: Flex__<"div">;
  text4?: Flex__<"div">;
  title4?: Flex__<"div">;
  paragraph4?: Flex__<"div">;
  schoolFoodservice2?: Flex__<"div">;
  text5?: Flex__<"div">;
  title5?: Flex__<"div">;
  paragraph5?: Flex__<"div">;
  convenienceStores2?: Flex__<"div">;
  text6?: Flex__<"div">;
  title6?: Flex__<"div">;
  paragraph6?: Flex__<"div">;
  ctaBottom?: Flex__<typeof CtaBottom>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultInnovationProps {}

const $$ = {
  fetchGraphQL: __fn_fetchGraphQL
};

export const serverQueryTree: QueryComponentNode = {
  type: "component",
  queries: {
    innovation: {
      id: "fetchGraphQL",
      fn: $$.fetchGraphQL,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = { method: "POST", url: null, request: null };
          __composite["url"] = "https://edit-sterling.dangstaging.org/graphql";
          __composite["request"] = {
            query:
              "query MyQuery {\n  pageBy(pageId: 201) {\n    pageContent {\n      fieldGroupName\n      button {\n        fieldGroupName\n        text\n        url\n      }\n      headlineParent {\n        fieldGroupName\n        headlinechild {\n          fieldGroupName\n          headlinefav\n          headlinenormal\n        }\n      }\n      textArea {\n        fieldGroupName\n        text\n      }\n    }\n  }\n}",
            variables: {}
          };
          return __composite;
        })()
      ]
    }
  },
  propsContext: {},
  stateSpecs: [],
  children: []
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInnovation__RenderFunc(props: {
  variants: PlasmicInnovation__VariantsArgs;
  args: PlasmicInnovation__ArgsType;
  overrides: PlasmicInnovation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $q = usePlasmicQueries(serverQueryTree, { $ctx, $props, $state: null });

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy($q),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uyaK17nhz8WhGjYZfKjMhX",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"pageContainer"}
            data-plasmic-override={overrides.pageContainer}
            className={classNames("all", sty.pageContainer)}
          >
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />

            <TopHero
              data-plasmic-name={"topHero"}
              data-plasmic-override={overrides.topHero}
              className={classNames("__wab_instance", sty.topHero)}
              pages={"innovation"}
            />

            <div
              data-plasmic-name={"innovationBody"}
              data-plasmic-override={overrides.innovationBody}
              className={classNames("all", sty.innovationBody)}
            >
              <div
                data-plasmic-name={"intro"}
                data-plasmic-override={overrides.intro}
                className={classNames("all", sty.intro)}
              >
                <div className={classNames("all", sty.freeBox___7JFur)}>
                  <h4
                    className={classNames(
                      "all",
                      "h4",
                      "h4__uyaK1",
                      "__wab_text",
                      sty.h4__jVlC8
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "desktop") ? (
                      <React.Fragment>
                        {
                          $q.innovation.data.body.data.pageBy.pageContent
                            .headlineParent[0].headlinechild[0].headlinefav
                        }
                      </React.Fragment>
                    ) : (
                      "From Insight to"
                    )}
                  </h4>
                  <h3
                    className={classNames(
                      "all",
                      "h3",
                      "h3__uyaK1",
                      "__wab_text",
                      sty.h3__onLfl,
                      hasVariant(globalVariants, "screen", "dualScreen")
                        ? "fave-script"
                        : "h3-script"
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "desktop") ? (
                      <React.Fragment>
                        {
                          $q.innovation.data.body.data.pageBy.pageContent
                            .headlineParent[0].headlinechild[0].headlinenormal
                        }
                      </React.Fragment>
                    ) : (
                      "Innovation"
                    )}
                  </h3>
                </div>
                <p
                  className={classNames(
                    "all",
                    "p",
                    "p__uyaK1",
                    "__wab_text",
                    sty.p___740UL
                  )}
                >
                  {hasVariant(globalVariants, "screen", "desktop") ? (
                    <React.Fragment>
                      {(() => {
                        try {
                          return $q.innovation.data.body.data.pageBy.pageContent
                            .textArea[0].text;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Sterling Foods serves a diverse range of foodservice and retail channels, delivering innovative bakery solutions tailored to the unique needs of each market. Our customer-first approach, flexible manufacturing capabilities, and commitment to quality help partners bring differentiated products to market with confidence.";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  ) : (
                    "At Sterling Foods, innovation begins with understanding your goals. Through a collaborative development process, technical expertise, and a passion for solving challenges, we help customers transform ideas into differentiated bakery solutions that meet evolving consumer demands."
                  )}
                </p>
                <p
                  className={classNames(
                    "all",
                    "p",
                    "p__uyaK1",
                    "__wab_text",
                    sty.p__tL3Ea
                  )}
                >
                  {hasVariant(globalVariants, "screen", "desktop") ? (
                    <React.Fragment>
                      {(() => {
                        try {
                          return $q.innovation.data.body.data.pageBy.pageContent
                            .textArea[1].text;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Sterling Foods serves a diverse range of foodservice and retail channels, delivering innovative bakery solutions tailored to the unique needs of each market. Our customer-first approach, flexible manufacturing capabilities, and commitment to quality help partners bring differentiated products to market with confidence.";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  ) : (
                    "Whether you're introducing a new product, refining an existing offering, or exploring emerging trends,\u0003our team partners with you every step of the way to bring your vision to life."
                  )}
                </p>
              </div>
              <div
                data-plasmic-name={"foodSafety"}
                data-plasmic-override={overrides.foodSafety}
                className={classNames("all", sty.foodSafety)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__i4Gd9)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "100%"
                      : hasVariant(globalVariants, "screen", "dualScreen")
                        ? "63.25%"
                        : hasVariant(globalVariants, "screen", "smallTablet")
                          ? "50%"
                          : hasVariant(globalVariants, "screen", "laptop")
                            ? "35%"
                            : hasVariant(
                                  globalVariants,
                                  "screen",
                                  "smallDesktop"
                                )
                              ? "472px"
                              : "574px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sterling_and_buena_vista_foods/images/sterlingFoodIceCreamAppleDessertPng.png",
                    fullWidth: 698,
                    fullHeight: 591,
                    aspectRatio: undefined
                  }}
                />

                <div
                  data-plasmic-name={"text"}
                  data-plasmic-override={overrides.text}
                  className={classNames("all", sty.text)}
                >
                  <div
                    data-plasmic-name={"title"}
                    data-plasmic-override={overrides.title}
                    className={classNames("all", sty.title)}
                  >
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__gOaLt
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .headlineParent[1].headlinechild[0].headlinefav
                          }
                        </React.Fragment>
                      ) : (
                        "Restaurants"
                      )}
                    </h4>
                    <h3
                      className={classNames(
                        "all",
                        "h3",
                        "h3__uyaK1",
                        "__wab_text",
                        sty.h3__oiZgu,
                        "h3-script"
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .headlineParent[1].headlinechild[0].headlinenormal
                          }
                        </React.Fragment>
                      ) : (
                        "National"
                      )}
                    </h3>
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__gc3Cv
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .headlineParent[1].headlinechild[1].headlinefav
                          }
                        </React.Fragment>
                      ) : (
                        "Restaurants"
                      )}
                    </h4>
                  </div>
                  <div
                    data-plasmic-name={"paragraph"}
                    data-plasmic-override={overrides.paragraph}
                    className={classNames("all", sty.paragraph)}
                  >
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p__bFdR
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .textArea[2].text
                          }
                        </React.Fragment>
                      ) : (
                        "Sterling Foods partners with leading restaurant chains to develop proprietary bakery solutions that support menu innovation, operational consistency, and speed to market. With a focus on uniqueness and operational ease, we help brands create iconic, signature products that stand apart from the crowd."
                      )}
                    </p>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"schoolFoodservice"}
                data-plasmic-override={overrides.schoolFoodservice}
                className={classNames("all", sty.schoolFoodservice)}
              >
                <div
                  data-plasmic-name={"text2"}
                  data-plasmic-override={overrides.text2}
                  className={classNames("all", sty.text2)}
                >
                  <div
                    data-plasmic-name={"title2"}
                    data-plasmic-override={overrides.title2}
                    className={classNames("all", sty.title2)}
                  >
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__vYjyw
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .headlineParent[2].headlinechild[0].headlinefav
                          }
                        </React.Fragment>
                      ) : (
                        "Foodservice"
                      )}
                    </h4>
                    <h3
                      className={classNames(
                        "all",
                        "h3",
                        "h3__uyaK1",
                        "__wab_text",
                        sty.h3__bkTtE,
                        "h3-script"
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .headlineParent[2].headlinechild[0].headlinenormal
                          }
                        </React.Fragment>
                      ) : (
                        "School"
                      )}
                    </h3>
                  </div>
                  <div
                    data-plasmic-name={"paragraph2"}
                    data-plasmic-override={overrides.paragraph2}
                    className={classNames("all", sty.paragraph2)}
                  >
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p__lzeA1
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .textArea[3].text
                          }
                        </React.Fragment>
                      ) : (
                        "Through our Buena Vista Foods division, Sterling Foods has been a trusted partner to K-12 nutrition programs for decades. We develop bakery solutions that seamlessly balance great taste, nutrition, and regulatory compliance\u2014helping school districts meet evolving nutritional standards while serving products students genuinely enjoy.  From clean label formulations to thoughtfully sourced, all natural ingredients, Buena Vista continues to set the standard in school nutrition."
                      )}
                    </p>
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p__uqu0Z
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .textArea[4].text
                          }
                        </React.Fragment>
                      ) : (
                        "Through our Buena Vista Foods division, Sterling Foods has been a trusted partner to K-12 nutrition programs for decades. We develop bakery solutions that seamlessly balance great taste, nutrition, and regulatory compliance\u2014helping school districts meet evolving nutritional standards while serving products students genuinely enjoy.  From clean label formulations to thoughtfully sourced, all natural ingredients, Buena Vista continues to set the standard in school nutrition."
                      )}
                    </p>
                    <PlasmicLink__
                      data-plasmic-name={"aboutUs"}
                      data-plasmic-override={overrides.aboutUs}
                      className={classNames(
                        "all",
                        "a",
                        "a__uyaK1",
                        sty.aboutUs
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PrimaryBtn
                        data-plasmic-name={"primaryBtn"}
                        data-plasmic-override={overrides.primaryBtn}
                        className={classNames("__wab_instance", sty.primaryBtn)}
                      >
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__nk7Mb
                          )}
                        >
                          {"Learn More About Buena Vista Foods"}
                        </div>
                      </PrimaryBtn>
                    </PlasmicLink__>
                  </div>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ey5TF)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "100%"
                      : hasVariant(globalVariants, "screen", "dualScreen")
                        ? "79.32%"
                        : hasVariant(globalVariants, "screen", "smallTablet")
                          ? "50%"
                          : hasVariant(globalVariants, "screen", "tablet")
                            ? "50%"
                            : hasVariant(
                                  globalVariants,
                                  "screen",
                                  "smallLaptop"
                                )
                              ? "40%"
                              : hasVariant(globalVariants, "screen", "laptop")
                                ? "40%"
                                : hasVariant(
                                      globalVariants,
                                      "screen",
                                      "smallDesktop"
                                    )
                                  ? "590px"
                                  : "697px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sterling_and_buena_vista_foods/images/sterlingFoodHamCheeseCroissantPng.png",
                    fullWidth: 732,
                    fullHeight: 550,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div
                data-plasmic-name={"convenienceStores"}
                data-plasmic-override={overrides.convenienceStores}
                className={classNames("all", sty.convenienceStores)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jkZr6)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "372px"
                      : "auto"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "100%"
                      : hasVariant(globalVariants, "screen", "dualScreen")
                        ? "85.94%"
                        : hasVariant(globalVariants, "screen", "smallTablet")
                          ? "50%"
                          : hasVariant(globalVariants, "screen", "tablet")
                            ? "47.46%"
                            : hasVariant(globalVariants, "screen", "laptop")
                              ? "40%"
                              : "698px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sterling_and_buena_vista_foods/images/sterlingFoodChocolateLavaCakePng.png",
                    fullWidth: 698,
                    fullHeight: 592,
                    aspectRatio: undefined
                  }}
                />

                <div
                  data-plasmic-name={"text3"}
                  data-plasmic-override={overrides.text3}
                  className={classNames("all", sty.text3)}
                >
                  <div
                    data-plasmic-name={"title3"}
                    data-plasmic-override={overrides.title3}
                    className={classNames("all", sty.title3)}
                  >
                    <h3
                      className={classNames(
                        "all",
                        "h3",
                        "h3__uyaK1",
                        "__wab_text",
                        sty.h3__iCLoB,
                        "h3-script"
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .headlineParent[3].headlinechild[0].headlinefav
                          }
                        </React.Fragment>
                      ) : (
                        "Convenience "
                      )}
                    </h3>
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__jNpL
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .headlineParent[3].headlinechild[0].headlinenormal
                          }
                        </React.Fragment>
                      ) : (
                        "Stores"
                      )}
                    </h4>
                  </div>
                  <p
                    className={classNames(
                      "all",
                      "p",
                      "p__uyaK1",
                      "__wab_text",
                      sty.p__fFzVi
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "desktop") ? (
                      <React.Fragment>
                        {
                          $q.innovation.data.body.data.pageBy.pageContent
                            .textArea[5].text
                        }
                      </React.Fragment>
                    ) : (
                      "Through our Buena Vista Foods division, Sterling Foods has been a trusted partner to K-12 nutrition programs for decades. We develop bakery solutions that seamlessly balance great taste, nutrition, and regulatory compliance\u2014helping school districts meet evolving nutritional standards while serving products students genuinely enjoy.  From clean label formulations to thoughtfully sourced, all natural ingredients, Buena Vista continues to set the standard in school nutrition."
                    )}
                  </p>
                  <div
                    data-plasmic-name={"paragraph3"}
                    data-plasmic-override={overrides.paragraph3}
                    className={classNames("all", sty.paragraph3)}
                  >
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p___1Hy0N
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          {
                            $q.innovation.data.body.data.pageBy.pageContent
                              .textArea[6].text
                          }
                        </React.Fragment>
                      ) : (
                        "Sterling Foods develops portable, individually wrapped bakery products and nutrition-focused snack solutions ideally suited for today's on-the-go consumer. From protein-forward snacks and nutrition bars to grab-and-go bakery offerings, our products help convenience retailers meet evolving consumer preferences."
                      )}
                    </p>
                  </div>
                </div>
              </div>
            </div>
            {(
              hasVariant(globalVariants, "screen", "desktop") ? true : false
            ) ? (
              <div
                data-plasmic-name={"innovationSection"}
                data-plasmic-override={overrides.innovationSection}
                className={classNames("all", sty.innovationSection)}
              >
                <div
                  data-plasmic-name={"intro2"}
                  data-plasmic-override={overrides.intro2}
                  className={classNames("all", sty.intro2)}
                >
                  <div className={classNames("all", sty.freeBox__mnnSn)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__syicM)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/sterling_and_buena_vista_foods/images/imagePng3.png",
                        fullWidth: 1525,
                        fullHeight: 417,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"foodSafety2"}
                  data-plasmic-override={overrides.foodSafety2}
                  className={classNames("all", sty.foodSafety2)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cnGjQ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : hasVariant(globalVariants, "screen", "dualScreen")
                          ? "63.25%"
                          : hasVariant(globalVariants, "screen", "smallTablet")
                            ? "60%"
                            : hasVariant(globalVariants, "screen", "laptop")
                              ? "35%"
                              : hasVariant(
                                    globalVariants,
                                    "screen",
                                    "smallDesktop"
                                  )
                                ? "472px"
                                : "574px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sterling_and_buena_vista_foods/images/sterlingFoodMiniQuichePng.png",
                      fullWidth: 575,
                      fullHeight: 482,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    data-plasmic-name={"text4"}
                    data-plasmic-override={overrides.text4}
                    className={classNames("all", sty.text4)}
                  >
                    <div
                      data-plasmic-name={"title4"}
                      data-plasmic-override={overrides.title4}
                      className={classNames("all", sty.title4)}
                    >
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__ldLzs
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .headlineParent[4].headlinechild[0].headlinefav
                            }
                          </React.Fragment>
                        ) : (
                          "Restaurants"
                        )}
                      </h4>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__uyaK1",
                          "__wab_text",
                          sty.h3__mYBy,
                          "h3-script"
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .headlineParent[4].headlinechild[0]
                                .headlinenormal
                            }
                          </React.Fragment>
                        ) : (
                          "National"
                        )}
                      </h3>
                    </div>
                    <div
                      data-plasmic-name={"paragraph4"}
                      data-plasmic-override={overrides.paragraph4}
                      className={classNames("all", sty.paragraph4)}
                    >
                      <p
                        className={classNames(
                          "all",
                          "p",
                          "p__uyaK1",
                          "__wab_text",
                          sty.p__b0Wok
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .textArea[7].text
                            }
                          </React.Fragment>
                        ) : (
                          "Sterling Foods partners with leading restaurant chains to develop proprietary bakery solutions that support menu innovation, operational consistency, and speed to market. With a focus on uniqueness and operational ease, we help brands create iconic, signature products that stand apart from the crowd."
                        )}
                      </p>
                      <p
                        className={classNames(
                          "all",
                          "p",
                          "p__uyaK1",
                          "__wab_text",
                          sty.p__bxJoi
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .textArea[8].text
                            }
                          </React.Fragment>
                        ) : (
                          "Sterling Foods partners with leading restaurant chains to develop proprietary bakery solutions that support menu innovation, operational consistency, and speed to market. With a focus on uniqueness and operational ease, we help brands create iconic, signature products that stand apart from the crowd."
                        )}
                      </p>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"schoolFoodservice2"}
                  data-plasmic-override={overrides.schoolFoodservice2}
                  className={classNames("all", sty.schoolFoodservice2)}
                >
                  <div
                    data-plasmic-name={"text5"}
                    data-plasmic-override={overrides.text5}
                    className={classNames("all", sty.text5)}
                  >
                    <div
                      data-plasmic-name={"title5"}
                      data-plasmic-override={overrides.title5}
                      className={classNames("all", sty.title5)}
                    >
                      <div className={classNames("all", sty.freeBox___3RUfV)}>
                        <h4
                          className={classNames(
                            "all",
                            "h4",
                            "h4__uyaK1",
                            "__wab_text",
                            sty.h4__vm8NE
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "desktop") ? (
                            <React.Fragment>
                              {
                                $q.innovation.data.body.data.pageBy.pageContent
                                  .headlineParent[5].headlinechild[0]
                                  .headlinefav
                              }
                            </React.Fragment>
                          ) : (
                            "Foodservice"
                          )}
                        </h4>
                        <h3
                          className={classNames(
                            "all",
                            "h3",
                            "h3__uyaK1",
                            "__wab_text",
                            sty.h3__bo1QB,
                            "h3-script"
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "desktop") ? (
                            <React.Fragment>
                              {
                                $q.innovation.data.body.data.pageBy.pageContent
                                  .headlineParent[5].headlinechild[0]
                                  .headlinenormal
                              }
                            </React.Fragment>
                          ) : (
                            "School"
                          )}
                        </h3>
                        <h4
                          className={classNames(
                            "all",
                            "h4",
                            "h4__uyaK1",
                            "__wab_text",
                            sty.h4__eDxZa
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "desktop") ? (
                            <React.Fragment>
                              {
                                $q.innovation.data.body.data.pageBy.pageContent
                                  .headlineParent[5].headlinechild[1]
                                  .headlinefav
                              }
                            </React.Fragment>
                          ) : (
                            "Foodservice"
                          )}
                        </h4>
                      </div>
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__aU4O
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .headlineParent[5].headlinechild[1]
                                .headlinenormal
                            }
                          </React.Fragment>
                        ) : (
                          "Foodservice"
                        )}
                      </h4>
                    </div>
                    <div
                      data-plasmic-name={"paragraph5"}
                      data-plasmic-override={overrides.paragraph5}
                      className={classNames("all", sty.paragraph5)}
                    >
                      <p
                        className={classNames(
                          "all",
                          "p",
                          "p__uyaK1",
                          "__wab_text",
                          sty.p__llpw
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .textArea[9].text
                            }
                          </React.Fragment>
                        ) : (
                          "Through our Buena Vista Foods division, Sterling Foods has been a trusted partner to K-12 nutrition programs for decades. We develop bakery solutions that seamlessly balance great taste, nutrition, and regulatory compliance\u2014helping school districts meet evolving nutritional standards while serving products students genuinely enjoy.  From clean label formulations to thoughtfully sourced, all natural ingredients, Buena Vista continues to set the standard in school nutrition."
                        )}
                      </p>
                      <p
                        className={classNames(
                          "all",
                          "p",
                          "p__uyaK1",
                          "__wab_text",
                          sty.p___1Jme
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .textArea[10].text
                            }
                          </React.Fragment>
                        ) : (
                          "Through our Buena Vista Foods division, Sterling Foods has been a trusted partner to K-12 nutrition programs for decades. We develop bakery solutions that seamlessly balance great taste, nutrition, and regulatory compliance\u2014helping school districts meet evolving nutritional standards while serving products students genuinely enjoy.  From clean label formulations to thoughtfully sourced, all natural ingredients, Buena Vista continues to set the standard in school nutrition."
                        )}
                      </p>
                    </div>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xVawJ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : hasVariant(globalVariants, "screen", "dualScreen")
                          ? "79.32%"
                          : hasVariant(globalVariants, "screen", "smallTablet")
                            ? "60%"
                            : hasVariant(globalVariants, "screen", "tablet")
                              ? "50%"
                              : hasVariant(
                                    globalVariants,
                                    "screen",
                                    "smallLaptop"
                                  )
                                ? "40%"
                                : hasVariant(globalVariants, "screen", "laptop")
                                  ? "40%"
                                  : hasVariant(
                                        globalVariants,
                                        "screen",
                                        "smallDesktop"
                                      )
                                    ? "590px"
                                    : "695px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sterling_and_buena_vista_foods/images/sterlingFoodPuffPastriesPng.png",
                      fullWidth: 695,
                      fullHeight: 611,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"convenienceStores2"}
                  data-plasmic-override={overrides.convenienceStores2}
                  className={classNames("all", sty.convenienceStores2)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__di6Wp)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "tablet")
                        ? "372px"
                        : "auto"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "auto"
                        : hasVariant(globalVariants, "screen", "dualScreen")
                          ? "85.94%"
                          : hasVariant(globalVariants, "screen", "smallTablet")
                            ? "auto"
                            : hasVariant(globalVariants, "screen", "tablet")
                              ? "47.46%"
                              : hasVariant(globalVariants, "screen", "laptop")
                                ? "40%"
                                : "574px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sterling_and_buena_vista_foods/images/sterlingFoodDessertWithFillingPng.png",
                      fullWidth: 575,
                      fullHeight: 482,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    data-plasmic-name={"text6"}
                    data-plasmic-override={overrides.text6}
                    className={classNames("all", sty.text6)}
                  >
                    <div
                      data-plasmic-name={"title6"}
                      data-plasmic-override={overrides.title6}
                      className={classNames("all", sty.title6)}
                    >
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__h5CIa
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .headlineParent[6].headlinechild[0].headlinefav
                            }
                          </React.Fragment>
                        ) : (
                          "Stores"
                        )}
                      </h4>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__uyaK1",
                          "__wab_text",
                          sty.h3__so0IA,
                          "h3-script"
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .headlineParent[6].headlinechild[0]
                                .headlinenormal
                            }
                          </React.Fragment>
                        ) : (
                          "Convenience "
                        )}
                      </h3>
                      <h4
                        className={classNames(
                          "all",
                          "h4",
                          "h4__uyaK1",
                          "__wab_text",
                          sty.h4__jTyNz
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .headlineParent[6].headlinechild[1].headlinefav
                            }
                          </React.Fragment>
                        ) : (
                          "Stores"
                        )}
                      </h4>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__uyaK1",
                          "__wab_text",
                          sty.h3__qpLid,
                          "h3-script"
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .headlineParent[6].headlinechild[1]
                                .headlinenormal
                            }
                          </React.Fragment>
                        ) : (
                          "Convenience "
                        )}
                      </h3>
                    </div>
                    <div
                      data-plasmic-name={"paragraph6"}
                      data-plasmic-override={overrides.paragraph6}
                      className={classNames("all", sty.paragraph6)}
                    >
                      <p
                        className={classNames(
                          "all",
                          "p",
                          "p__uyaK1",
                          "__wab_text",
                          sty.p__wwxfl
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "desktop") ? (
                          <React.Fragment>
                            {
                              $q.innovation.data.body.data.pageBy.pageContent
                                .textArea[11].text
                            }
                          </React.Fragment>
                        ) : (
                          "Sterling Foods develops portable, individually wrapped bakery products and nutrition-focused snack solutions ideally suited for today's on-the-go consumer. From protein-forward snacks and nutrition bars to grab-and-go bakery offerings, our products help convenience retailers meet evolving consumer preferences."
                        )}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            <CtaBottom
              data-plasmic-name={"ctaBottom"}
              data-plasmic-override={overrides.ctaBottom}
              className={classNames("__wab_instance", sty.ctaBottom)}
            />

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageContainer",
    "header",
    "topHero",
    "innovationBody",
    "intro",
    "foodSafety",
    "text",
    "title",
    "paragraph",
    "schoolFoodservice",
    "text2",
    "title2",
    "paragraph2",
    "aboutUs",
    "primaryBtn",
    "convenienceStores",
    "text3",
    "title3",
    "paragraph3",
    "innovationSection",
    "intro2",
    "foodSafety2",
    "text4",
    "title4",
    "paragraph4",
    "schoolFoodservice2",
    "text5",
    "title5",
    "paragraph5",
    "convenienceStores2",
    "text6",
    "title6",
    "paragraph6",
    "ctaBottom",
    "footer"
  ],
  pageContainer: [
    "pageContainer",
    "header",
    "topHero",
    "innovationBody",
    "intro",
    "foodSafety",
    "text",
    "title",
    "paragraph",
    "schoolFoodservice",
    "text2",
    "title2",
    "paragraph2",
    "aboutUs",
    "primaryBtn",
    "convenienceStores",
    "text3",
    "title3",
    "paragraph3",
    "innovationSection",
    "intro2",
    "foodSafety2",
    "text4",
    "title4",
    "paragraph4",
    "schoolFoodservice2",
    "text5",
    "title5",
    "paragraph5",
    "convenienceStores2",
    "text6",
    "title6",
    "paragraph6",
    "ctaBottom",
    "footer"
  ],
  header: ["header"],
  topHero: ["topHero"],
  innovationBody: [
    "innovationBody",
    "intro",
    "foodSafety",
    "text",
    "title",
    "paragraph",
    "schoolFoodservice",
    "text2",
    "title2",
    "paragraph2",
    "aboutUs",
    "primaryBtn",
    "convenienceStores",
    "text3",
    "title3",
    "paragraph3"
  ],
  intro: ["intro"],
  foodSafety: ["foodSafety", "text", "title", "paragraph"],
  text: ["text", "title", "paragraph"],
  title: ["title"],
  paragraph: ["paragraph"],
  schoolFoodservice: [
    "schoolFoodservice",
    "text2",
    "title2",
    "paragraph2",
    "aboutUs",
    "primaryBtn"
  ],
  text2: ["text2", "title2", "paragraph2", "aboutUs", "primaryBtn"],
  title2: ["title2"],
  paragraph2: ["paragraph2", "aboutUs", "primaryBtn"],
  aboutUs: ["aboutUs", "primaryBtn"],
  primaryBtn: ["primaryBtn"],
  convenienceStores: ["convenienceStores", "text3", "title3", "paragraph3"],
  text3: ["text3", "title3", "paragraph3"],
  title3: ["title3"],
  paragraph3: ["paragraph3"],
  innovationSection: [
    "innovationSection",
    "intro2",
    "foodSafety2",
    "text4",
    "title4",
    "paragraph4",
    "schoolFoodservice2",
    "text5",
    "title5",
    "paragraph5",
    "convenienceStores2",
    "text6",
    "title6",
    "paragraph6"
  ],
  intro2: ["intro2"],
  foodSafety2: ["foodSafety2", "text4", "title4", "paragraph4"],
  text4: ["text4", "title4", "paragraph4"],
  title4: ["title4"],
  paragraph4: ["paragraph4"],
  schoolFoodservice2: ["schoolFoodservice2", "text5", "title5", "paragraph5"],
  text5: ["text5", "title5", "paragraph5"],
  title5: ["title5"],
  paragraph5: ["paragraph5"],
  convenienceStores2: ["convenienceStores2", "text6", "title6", "paragraph6"],
  text6: ["text6", "title6", "paragraph6"],
  title6: ["title6"],
  paragraph6: ["paragraph6"],
  ctaBottom: ["ctaBottom"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageContainer: "div";
  header: typeof Header;
  topHero: typeof TopHero;
  innovationBody: "div";
  intro: "div";
  foodSafety: "div";
  text: "div";
  title: "div";
  paragraph: "div";
  schoolFoodservice: "div";
  text2: "div";
  title2: "div";
  paragraph2: "div";
  aboutUs: "a";
  primaryBtn: typeof PrimaryBtn;
  convenienceStores: "div";
  text3: "div";
  title3: "div";
  paragraph3: "div";
  innovationSection: "div";
  intro2: "div";
  foodSafety2: "div";
  text4: "div";
  title4: "div";
  paragraph4: "div";
  schoolFoodservice2: "div";
  text5: "div";
  title5: "div";
  paragraph5: "div";
  convenienceStores2: "div";
  text6: "div";
  title6: "div";
  paragraph6: "div";
  ctaBottom: typeof CtaBottom;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInnovation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInnovation__VariantsArgs;
    args?: PlasmicInnovation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicInnovation__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicInnovation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicInnovation__ArgProps,
          internalVariantPropNames: PlasmicInnovation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicInnovation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInnovation";
  } else {
    func.displayName = `PlasmicInnovation.${nodeName}`;
  }
  return func;
}

export const PlasmicInnovation = Object.assign(
  // Top-level PlasmicInnovation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageContainer: makeNodeComponent("pageContainer"),
    header: makeNodeComponent("header"),
    topHero: makeNodeComponent("topHero"),
    innovationBody: makeNodeComponent("innovationBody"),
    intro: makeNodeComponent("intro"),
    foodSafety: makeNodeComponent("foodSafety"),
    text: makeNodeComponent("text"),
    title: makeNodeComponent("title"),
    paragraph: makeNodeComponent("paragraph"),
    schoolFoodservice: makeNodeComponent("schoolFoodservice"),
    text2: makeNodeComponent("text2"),
    title2: makeNodeComponent("title2"),
    paragraph2: makeNodeComponent("paragraph2"),
    aboutUs: makeNodeComponent("aboutUs"),
    primaryBtn: makeNodeComponent("primaryBtn"),
    convenienceStores: makeNodeComponent("convenienceStores"),
    text3: makeNodeComponent("text3"),
    title3: makeNodeComponent("title3"),
    paragraph3: makeNodeComponent("paragraph3"),
    innovationSection: makeNodeComponent("innovationSection"),
    intro2: makeNodeComponent("intro2"),
    foodSafety2: makeNodeComponent("foodSafety2"),
    text4: makeNodeComponent("text4"),
    title4: makeNodeComponent("title4"),
    paragraph4: makeNodeComponent("paragraph4"),
    schoolFoodservice2: makeNodeComponent("schoolFoodservice2"),
    text5: makeNodeComponent("text5"),
    title5: makeNodeComponent("title5"),
    paragraph5: makeNodeComponent("paragraph5"),
    convenienceStores2: makeNodeComponent("convenienceStores2"),
    text6: makeNodeComponent("text6"),
    title6: makeNodeComponent("title6"),
    paragraph6: makeNodeComponent("paragraph6"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicInnovation
    internalVariantProps: PlasmicInnovation__VariantProps,
    internalArgProps: PlasmicInnovation__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/innovation",
      pagePath: "/innovation",
      params: {},
      query: {}
    })
  }
);

export default PlasmicInnovation;
/* prettier-ignore-end */
