/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: -6leV5wneOe9

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicMenuList.module.css"; // plasmic-import: -6leV5wneOe9/css

createPlasmicElementProxy;

export type PlasmicMenuList__VariantMembers = {
  current:
    | "aboutUs"
    | "capabilities"
    | "markets"
    | "ourFacilities"
    | "qualitySafety"
    | "careers";
};
export type PlasmicMenuList__VariantsArgs = {
  current?: SingleChoiceArg<
    | "aboutUs"
    | "capabilities"
    | "markets"
    | "ourFacilities"
    | "qualitySafety"
    | "careers"
  >;
};
type VariantPropType = keyof PlasmicMenuList__VariantsArgs;
export const PlasmicMenuList__VariantProps = new Array<VariantPropType>(
  "current"
);

export type PlasmicMenuList__ArgsType = {};
type ArgPropType = keyof PlasmicMenuList__ArgsType;
export const PlasmicMenuList__ArgProps = new Array<ArgPropType>();

export type PlasmicMenuList__OverridesType = {
  menuList?: Flex__<"div">;
};

export interface DefaultMenuListProps {
  current?: SingleChoiceArg<
    | "aboutUs"
    | "capabilities"
    | "markets"
    | "ourFacilities"
    | "qualitySafety"
    | "careers"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMenuList__RenderFunc(props: {
  variants: PlasmicMenuList__VariantsArgs;
  args: PlasmicMenuList__ArgsType;
  overrides: PlasmicMenuList__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "current",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return {
                "/about-us": "aboutUs",
                "/capabilities": "capabilities",
                "/markets": "markets",
                "/our-facilities": "ourFacilities",
                "/quality-safety": "qualitySafety",
                "/careers": "careers"
              }[typeof location !== "undefined" ? location.pathname : ""];
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.current
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"menuList"}
      data-plasmic-override={overrides.menuList}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uyaK17nhz8WhGjYZfKjMhX",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.menuList
      )}
    >
      <PlasmicLink__
        className={classNames("all", "a", "a__uyaK1", sty.link___3RaYy)}
        component={Link}
        href={
          hasVariant(globalVariants, "screen", "large")
            ? `/about-us`
            : "/about-us"
        }
        legacyBehavior={false}
        platform={"nextjs"}
      >
        <div
          className={classNames("all", "__wab_text", sty.text__egVfI, {
            [sty.textcurrent_aboutUs__egVfI1RAfk]: hasVariant(
              $state,
              "current",
              "aboutUs"
            )
          })}
          style={
            hasVariant($state, "current", "aboutUs")
              ? {
                  textDecorationColor: "var(--token-VSsNRyw2VYkH)",
                  textUnderlineOffset: "4px"
                }
              : undefined
          }
        >
          {"About Us"}
        </div>
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames("all", "a", "a__uyaK1", sty.link__hUnhB)}
        component={Link}
        href={
          hasVariant(globalVariants, "screen", "large")
            ? `/capabilities`
            : "/capabilities"
        }
        legacyBehavior={false}
        platform={"nextjs"}
      >
        <div
          className={classNames("all", "__wab_text", sty.text__vX5PD, {
            [sty.textcurrent_capabilities__vX5PDnWrPh]: hasVariant(
              $state,
              "current",
              "capabilities"
            )
          })}
          style={
            hasVariant($state, "current", "capabilities")
              ? {
                  textDecorationColor: "var(--token-VSsNRyw2VYkH)",
                  textUnderlineOffset: "4px"
                }
              : undefined
          }
        >
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__uyaK1"
              }
              style={{ color: "var(--token-Gx156sR9ht1r)" }}
            >
              {"Capabilties"}
            </span>
          </React.Fragment>
        </div>
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames("all", "a", "a__uyaK1", sty.link__nl7P)}
        component={Link}
        href={
          hasVariant(globalVariants, "screen", "large")
            ? `/markets`
            : "/markets"
        }
        legacyBehavior={false}
        platform={"nextjs"}
      >
        <div
          className={classNames("all", "__wab_text", sty.text___0V80P, {
            [sty.textcurrent_markets___0V80PIcs7Q]: hasVariant(
              $state,
              "current",
              "markets"
            )
          })}
          style={
            hasVariant($state, "current", "markets")
              ? {
                  textDecorationColor: "var(--token-VSsNRyw2VYkH)",
                  textUnderlineOffset: "4px"
                }
              : undefined
          }
        >
          {"Markets"}
        </div>
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames("all", "a", "a__uyaK1", sty.link__djjcq)}
        component={Link}
        href={
          hasVariant(globalVariants, "screen", "large")
            ? `/our-facilities`
            : "/our-facilities"
        }
        legacyBehavior={false}
        platform={"nextjs"}
      >
        <div
          className={classNames("all", "__wab_text", sty.text__kOnNl, {
            [sty.textcurrent_ourFacilities__kOnNl8BTpx]: hasVariant(
              $state,
              "current",
              "ourFacilities"
            )
          })}
          style={
            hasVariant($state, "current", "ourFacilities")
              ? {
                  textDecorationColor: "var(--token-VSsNRyw2VYkH)",
                  textUnderlineOffset: "4px"
                }
              : undefined
          }
        >
          {"Our Facilities"}
        </div>
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames("all", "a", "a__uyaK1", sty.link__n0Rjz)}
        component={Link}
        href={
          hasVariant(globalVariants, "screen", "large")
            ? `/quality-safety`
            : "/quality-safety"
        }
        legacyBehavior={false}
        platform={"nextjs"}
      >
        <div
          className={classNames("all", "__wab_text", sty.text___11Aoz, {
            [sty.textcurrent_qualitySafety___11AozvZhXb]: hasVariant(
              $state,
              "current",
              "qualitySafety"
            )
          })}
          style={
            hasVariant($state, "current", "qualitySafety")
              ? {
                  textDecorationColor: "var(--token-VSsNRyw2VYkH)",
                  textUnderlineOffset: "4px"
                }
              : undefined
          }
        >
          {"Quality & Safety"}
        </div>
      </PlasmicLink__>
      <PlasmicLink__
        className={classNames("all", "a", "a__uyaK1", sty.link___5USgH)}
        component={Link}
        href={
          hasVariant(globalVariants, "screen", "large")
            ? `/careers`
            : "/careers"
        }
        legacyBehavior={false}
        platform={"nextjs"}
      >
        <div
          className={classNames("all", "__wab_text", sty.text__eLs7R, {
            [sty.textcurrent_careers__eLs7RgAaqf]: hasVariant(
              $state,
              "current",
              "careers"
            )
          })}
          style={
            hasVariant($state, "current", "careers")
              ? {
                  textDecorationColor: "var(--token-VSsNRyw2VYkH)",
                  textUnderlineOffset: "4px"
                }
              : undefined
          }
        >
          {"Careers"}
        </div>
      </PlasmicLink__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  menuList: ["menuList"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  menuList: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuList__VariantsArgs;
    args?: PlasmicMenuList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMenuList__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMenuList__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMenuList__ArgProps,
          internalVariantPropNames: PlasmicMenuList__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMenuList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "menuList") {
    func.displayName = "PlasmicMenuList";
  } else {
    func.displayName = `PlasmicMenuList.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuList = Object.assign(
  // Top-level PlasmicMenuList renders the root element
  makeNodeComponent("menuList"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMenuList
    internalVariantProps: PlasmicMenuList__VariantProps,
    internalArgProps: PlasmicMenuList__ArgProps
  }
);

export default PlasmicMenuList;
/* prettier-ignore-end */
