/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uyaK17nhz8WhGjYZfKjMhX
// Component: 5hAHrj7TAU1C

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import Header from "../../Header"; // plasmic-import: qmNXHiKWCTTQ/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import PrimaryBtn from "../../PrimaryBtn"; // plasmic-import: TiffCyYLfuDQ/component
import SecondaryBtn from "../../SecondaryBtn"; // plasmic-import: r3QPz6kMc0wE/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import Footer from "../../Footer"; // plasmic-import: RbMtVh1ii_PZ/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uyaK17nhz8WhGjYZfKjMhX/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHome.module.css"; // plasmic-import: 5hAHrj7TAU1C/css

import CaretLeftSmSvgrepoComSvgIcon from "./icons/PlasmicIcon__CaretLeftSmSvgrepoComSvg"; // plasmic-import: Fos_YVXKTavi/icon
import CaretRightSmSvgrepoComSvgIcon from "./icons/PlasmicIcon__CaretRightSmSvgrepoComSvg"; // plasmic-import: 9p31HanEpOae/icon
import StarFilledIcon from "./icons/PlasmicIcon__StarFilled"; // plasmic-import: QmvyYi5qQaXv/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "sterling-foods-homepage",

    openGraph: {
      title: "sterling-foods-homepage"
    },
    twitter: {
      card: "summary" as const,
      title: "sterling-foods-homepage"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  homepage?: Flex__<"div">;
  header?: Flex__<"div">;
  homeHero?: Flex__<"div">;
  title?: Flex__<"div">;
  h1?: Flex__<"h1">;
  homeBody?: Flex__<"div">;
  intro?: Flex__<"div">;
  text3?: Flex__<"div">;
  title2?: Flex__<"div">;
  section?: Flex__<"div">;
  section2?: Flex__<"div">;
  bakerysolutions?: Flex__<"div">;
  image?: Flex__<"div">;
  text?: Flex__<"div">;
  section3?: Flex__<"div">;
  foodServiceAndRetailPartners?: Flex__<"div">;
  text2?: Flex__<"div">;
  image2?: Flex__<"div">;
  innovationResponsive?: Flex__<"div">;
  buttons?: Flex__<"div">;
  reviews?: Flex__<"div">;
  frame36?: Flex__<"div">;
  frame34?: Flex__<"div">;
  frame35?: Flex__<"div">;
  frame43?: Flex__<"div">;
  frame44?: Flex__<"div">;
  sliderCarousel?: Flex__<typeof SliderWrapper>;
  box?: Flex__<"div">;
  child?: Flex__<"div">;
  box2?: Flex__<"div">;
  child2?: Flex__<"div">;
  box3?: Flex__<"div">;
  child3?: Flex__<"div">;
  box4?: Flex__<"div">;
  child4?: Flex__<"div">;
  cta?: Flex__<"div">;
  frame52?: Flex__<"div">;
  buttonContainer?: Flex__<"div">;
  homeFooter?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => 0,

        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $q: {},
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    query: usePlasmicDataOp(() => {
      return {
        sourceId: "oysuYFSoAdb9rhuPV27pRM",
        opId: "85250640-d5f9-469f-87b2-b55311438201",
        userArgs: {},
        cacheKey: `plasmic.$.85250640-d5f9-469f-87b2-b55311438201.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    wpGraph: usePlasmicDataOp(() => {
      return {
        sourceId: "oysuYFSoAdb9rhuPV27pRM",
        opId: "e5527222-d05e-4811-818d-6e29fa6a8a6c",
        userArgs: {},
        cacheKey: `plasmic.$.e5527222-d05e-4811-818d-6e29fa6a8a6c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"homepage"}
          data-plasmic-override={overrides.homepage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uyaK17nhz8WhGjYZfKjMhX",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.homepage,
            ""
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("all", sty.header)}
          >
            <Header
              className={classNames("__wab_instance", sty.header__o4Nex)}
            />
          </div>
          <div
            data-plasmic-name={"homeHero"}
            data-plasmic-override={overrides.homeHero}
            className={classNames("all", sty.homeHero)}
          >
            <Reveal
              className={classNames("__wab_instance", sty.reveal__qyrRe)}
              triggerOnce={true}
            >
              <div
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames("all", sty.title)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    "all",
                    "h1",
                    "h1__uyaK1",
                    "__wab_text",
                    sty.h1,
                    hasVariant(globalVariants, "screen", "desktop")
                      ? "cambria-lineheight"
                      : undefined
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $queries.wpGraph.data.response.data.pageBy
                          .pageContent.content[0].headline;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    "all",
                    "__wab_text",
                    sty.text___4TbN,
                    "h1-script"
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $queries.wpGraph.data.response.data.pageBy
                          .pageContent.content[1].headline;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "like no other.";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
            </Reveal>
            <div className={classNames("all", sty.freeBox__bc7O)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ij4Ls)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/sterling_and_buena_vista_foods/images/bakedgoodsAvif2.avif",
                  fullWidth: 1154,
                  fullHeight: 740,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <div
            data-plasmic-name={"homeBody"}
            data-plasmic-override={overrides.homeBody}
            className={classNames("all", sty.homeBody)}
          >
            <div className={classNames("all", sty.freeBox___9VvCh)}>
              <div
                data-plasmic-name={"intro"}
                data-plasmic-override={overrides.intro}
                className={classNames(
                  "all",
                  sty.intro,
                  hasVariant(globalVariants, "screen", "desktop")
                    ? "cambria-lineheight"
                    : undefined
                )}
              >
                <Reveal
                  className={classNames("__wab_instance", sty.reveal___5Ma6E)}
                  triggerOnce={true}
                >
                  <div
                    data-plasmic-name={"text3"}
                    data-plasmic-override={overrides.text3}
                    className={classNames("all", sty.text3)}
                  >
                    <div
                      data-plasmic-name={"title2"}
                      data-plasmic-override={overrides.title2}
                      className={classNames("all", sty.title2)}
                    >
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__kyQgx,
                          "h3-script"
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.wpGraph.data.response.data.pageBy
                                .pageContent.content[2].headline;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Custom-crafted";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__uyaK1",
                          "__wab_text",
                          sty.h3__wdfVl,
                          hasVariant(globalVariants, "screen", "desktop")
                            ? "cambria-lineheight"
                            : undefined
                        )}
                      >
                        {"baked goods and snack solutions"}
                      </h3>
                    </div>
                    <h3
                      className={classNames(
                        "all",
                        "h3",
                        "h3__uyaK1",
                        "__wab_text",
                        sty.h3__nYLeh,
                        hasVariant(globalVariants, "screen", "desktop")
                          ? "cambria-lineheight"
                          : undefined
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "laptop") ? (
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <h3
                              className={classNames(
                                "all",
                                "h3",
                                "h3__uyaK1",
                                "__wab_text",
                                sty.h3__kuEAs
                              )}
                            >
                              {hasVariant(globalVariants, "screen", "laptop")
                                ? "made to meet the demands of today\u2019s foodservice, retail, and convenience markets."
                                : "made to meet the demands of today\u2019s foodservice, retail, and convenience markets."}
                            </h3>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      ) : hasVariant(globalVariants, "screen", "desktop") ? (
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <h3
                              className={classNames(
                                "all",
                                "h3",
                                "h3__uyaK1",
                                "__wab_text",
                                sty.h3___0Sw2Y
                              )}
                            >
                              {
                                "made to meet the demands of today\u2019s foodservice, retail, and convenience markets."
                              }
                            </h3>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      ) : (
                        "made to meet the demands of today\u2019s foodservice, retail, and convenience markets."
                      )}
                    </h3>
                  </div>
                </Reveal>
                <div className={classNames("all", sty.freeBox__e8GY)}>
                  <p
                    className={classNames(
                      "all",
                      "p",
                      "p__uyaK1",
                      "__wab_text",
                      sty.p__w18L
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.wpGraph.data.response.data.pageBy
                            .pageContent.textArea[0].text;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "At Sterling Foods, we combine bakery expertise, innovation, and leading-edge technology to create products that perform.";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </p>
                  <p
                    className={classNames(
                      "all",
                      "p",
                      "p__uyaK1",
                      "__wab_text",
                      sty.p__jid1W
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.wpGraph.data.response.data.pageBy
                            .pageContent.textArea[1].text;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "From restaurants and non-commercial foodservice to convenience stores and in-store bakeries, we partner with our customers to deliver high-quality baked goods and snack products tailored to their needs.";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </p>
                </div>
                <div className={classNames("all", sty.freeBox__v56Y6)}>
                  <PrimaryBtn
                    className={classNames(
                      "__wab_instance",
                      sty.primaryBtn__h8Wfb
                    )}
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__cEfj0
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.wpGraph.data.response.data.pageBy
                              .pageContent.button[0].text;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Start Your Project";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </PrimaryBtn>
                  <PrimaryBtn
                    className={classNames(
                      "__wab_instance",
                      sty.primaryBtn__bH4Ix
                    )}
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__ye4QN
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.wpGraph.data.response.data.pageBy
                              .pageContent.button[1].text;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Learn More About Sterling Foods";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </PrimaryBtn>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames("all", sty.section)}
            >
              <div
                data-plasmic-name={"section2"}
                data-plasmic-override={overrides.section2}
                className={classNames("all", sty.section2)}
              >
                <div
                  data-plasmic-name={"bakerysolutions"}
                  data-plasmic-override={overrides.bakerysolutions}
                  className={classNames("all", sty.bakerysolutions)}
                >
                  <div
                    data-plasmic-name={"image"}
                    data-plasmic-override={overrides.image}
                    className={classNames("all", sty.image)}
                  />

                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames("all", sty.text)}
                  >
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__s33Bh,
                        "h4-script"
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.wpGraph.data.response.data.pageBy
                              .pageContent.content[3].headline;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Bakery Solutions";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </h4>
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4___4Rj2M
                      )}
                    >
                      {"Built for Today\u2019s Market"}
                    </h4>
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p___37Rkd
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.wpGraph.data.response.data.pageBy
                              .pageContent.textArea[2].text;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "We understand that consumer tastes, operational needs, and market demands are always evolving. That\u2019s why we take a flexible, can-do approach to product development, production, and partnership.\nOur team works with you to create bakery solutions that are consistent, scalable, and made with quality and food safety at the forefront.";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </p>
                    <PrimaryBtn
                      className={classNames(
                        "__wab_instance",
                        sty.primaryBtn__sB6Y
                      )}
                    >
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__tzNq
                        )}
                      >
                        {"Explore Product Capabilities"}
                      </div>
                    </PrimaryBtn>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"section3"}
                data-plasmic-override={overrides.section3}
                className={classNames("all", sty.section3)}
              >
                <div
                  data-plasmic-name={"foodServiceAndRetailPartners"}
                  data-plasmic-override={overrides.foodServiceAndRetailPartners}
                  className={classNames(
                    "all",
                    sty.foodServiceAndRetailPartners
                  )}
                >
                  <div
                    data-plasmic-name={"text2"}
                    data-plasmic-override={overrides.text2}
                    className={classNames("all", sty.text2)}
                  >
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__ynMJ,
                        "h4-script"
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.wpGraph.data.response.data.pageBy
                              .pageContent.content[4].headline;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Serving a Wide Range of";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </h4>
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__lgHx
                      )}
                    >
                      {"Foodservice and Retail Partners"}
                    </h4>
                    <p
                      className={classNames(
                        "all",
                        "p",
                        "p__uyaK1",
                        "__wab_text",
                        sty.p__xZzR
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.wpGraph.data.response.data.pageBy
                              .pageContent.textArea[3].text;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Sterling Foods proudly serves:";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </p>
                    <div className={classNames("all", sty.freeBox__tCUx)}>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__hP5Xl
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                "all",
                                "ul",
                                "ul__uyaK1",
                                sty.ul__wbQ3C
                              )}
                            >
                              <li
                                className={classNames(
                                  "all",
                                  "li",
                                  "li__uyaK1",
                                  "__wab_text",
                                  sty.li__aVfbp
                                )}
                              >
                                {"National Restaurants"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                "all",
                                "ul",
                                "ul__uyaK1",
                                sty.ul___45Go2
                              )}
                            >
                              <li
                                className={classNames(
                                  "all",
                                  "li",
                                  "li__uyaK1",
                                  "__wab_text",
                                  sty.li__yu0Ad
                                )}
                              >
                                {"Convenience Stores"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                "all",
                                "ul",
                                "ul__uyaK1",
                                sty.ul___5A4Y
                              )}
                            >
                              <li
                                className={classNames(
                                  "all",
                                  "li",
                                  "li__uyaK1",
                                  "__wab_text",
                                  sty.li___4UrCd
                                )}
                              >
                                {"In-Store Bakery"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text___6LhDw
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                "all",
                                "ul",
                                "ul__uyaK1",
                                sty.ul___87S4A
                              )}
                            >
                              <li
                                className={classNames(
                                  "all",
                                  "li",
                                  "li__uyaK1",
                                  "__wab_text",
                                  sty.li__t9KMp
                                )}
                              >
                                {"School Foodservice"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                "all",
                                "ul",
                                "ul__uyaK1",
                                sty.ul__y9JOz
                              )}
                            >
                              <li
                                className={classNames(
                                  "all",
                                  "li",
                                  "li__uyaK1",
                                  "__wab_text",
                                  sty.li__vcYgl
                                )}
                              >
                                {"Military"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                    <PrimaryBtn
                      className={classNames(
                        "__wab_instance",
                        sty.primaryBtn__gurqP
                      )}
                    >
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__c0Kxh
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.wpGraph.data.response.data.pageBy
                                .pageContent.button[3].text;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "View All Markets";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </PrimaryBtn>
                  </div>
                  <div
                    data-plasmic-name={"image2"}
                    data-plasmic-override={overrides.image2}
                    className={classNames("all", sty.image2)}
                  />
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"innovationResponsive"}
              data-plasmic-override={overrides.innovationResponsive}
              className={classNames("all", sty.innovationResponsive)}
            >
              <div className={classNames("all", sty.column__dW8Wt)}>
                <div className={classNames("all", sty.freeBox__r7Arz)} />
              </div>
              <div className={classNames("all", sty.column__f0O4)}>
                <div className={classNames("all", sty.freeBox__gD3PN)}>
                  <div className={classNames("all", sty.freeBox__cBh8C)}>
                    <h4
                      className={classNames(
                        "all",
                        "h4",
                        "h4__uyaK1",
                        "__wab_text",
                        sty.h4__gwMWe
                      )}
                    >
                      {"Innovation. Quality. "}
                    </h4>
                    <h3
                      className={classNames(
                        "all",
                        "h3",
                        "h3__uyaK1",
                        "__wab_text",
                        sty.h3__vQRj1,
                        "h4-script"
                      )}
                    >
                      {"Partnership."}
                    </h3>
                  </div>
                  <p
                    className={classNames(
                      "all",
                      "p",
                      "p__uyaK1",
                      "__wab_text",
                      sty.p__pbUxp
                    )}
                  >
                    {
                      "What sets Sterling Foods apart is more than what we bake. It\u2019s how we partner.\n\n\rWith a commitment to innovation, flexible capabilities, and uncompromising standards for quality and food safety, we help our customers bring bakery and snack products to market with confidence."
                    }
                  </p>
                  <div
                    data-plasmic-name={"buttons"}
                    data-plasmic-override={overrides.buttons}
                    className={classNames("all", sty.buttons)}
                  >
                    <SecondaryBtn
                      className={classNames(
                        "__wab_instance",
                        sty.secondaryBtn__pKcaL
                      )}
                    >
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__udAml
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.wpGraph.data.response.data.pageBy
                                .pageContent.button[4].text;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "View Our Facilities";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </SecondaryBtn>
                    <SecondaryBtn
                      className={classNames(
                        "__wab_instance",
                        sty.secondaryBtn__xb607
                      )}
                    >
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__acejO
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.wpGraph.data.response.data.pageBy
                                .pageContent.button[5].text;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Explore Quality & Safety";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </SecondaryBtn>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"reviews"}
              data-plasmic-override={overrides.reviews}
              className={classNames("all", sty.reviews)}
            >
              <div
                data-plasmic-name={"frame36"}
                data-plasmic-override={overrides.frame36}
                className={classNames("all", sty.frame36)}
              >
                <div
                  data-plasmic-name={"frame34"}
                  data-plasmic-override={overrides.frame34}
                  className={classNames("all", sty.frame34)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__absOp)}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {"Fresh Out of the Oven "}
                      </React.Fragment>
                      {
                        <span
                          className={classNames(
                            "all",
                            "span",
                            "span__uyaK1",
                            "__wab_text",
                            "plasmic_default__inline",
                            sty.span__tUu4S
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "desktop") ? (
                            <React.Fragment>
                              {
                                $queries.wpGraph.data.response.data.pageBy
                                  .pageContent.content[6].headline
                              }
                            </React.Fragment>
                          ) : hasVariant(globalVariants, "screen", "large") ? (
                            <React.Fragment>
                              {
                                $queries.wpGraph.data.response.data.pageBy
                                  .pageContent.content[6].headline
                              }
                            </React.Fragment>
                          ) : (
                            <React.Fragment>
                              {
                                $queries.query.data.response.data.page
                                  .pageContent.content[6].headline
                              }
                            </React.Fragment>
                          )}
                        </span>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div
                  data-plasmic-name={"frame35"}
                  data-plasmic-override={overrides.frame35}
                  className={classNames("all", sty.frame35)}
                >
                  <div
                    data-plasmic-name={"frame43"}
                    data-plasmic-override={overrides.frame43}
                    className={classNames("all", sty.frame43)}
                  >
                    <CaretLeftSmSvgrepoComSvgIcon
                      className={classNames("all", sty.svg__rnGj)}
                      onClick={async event => {
                        const $steps = {};

                        $steps["runActionOnSliderCarousel"] = true
                          ? (() => {
                              const actionArgs = {
                                tplRef: "sliderCarousel",
                                action: "slickPrev"
                              };
                              return (({ tplRef, action, args }) => {
                                return $refs?.[tplRef]?.[action]?.(
                                  ...(args ?? [])
                                );
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["runActionOnSliderCarousel"] != null &&
                          typeof $steps["runActionOnSliderCarousel"] ===
                            "object" &&
                          typeof $steps["runActionOnSliderCarousel"].then ===
                            "function"
                        ) {
                          $steps["runActionOnSliderCarousel"] =
                            await $steps["runActionOnSliderCarousel"];
                        }
                      }}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame44"}
                    data-plasmic-override={overrides.frame44}
                    className={classNames("all", sty.frame44)}
                  >
                    <CaretRightSmSvgrepoComSvgIcon
                      className={classNames("all", sty.svg__eZaTs)}
                      onClick={async event => {
                        const $steps = {};

                        $steps["runActionOnSliderCarousel"] = true
                          ? (() => {
                              const actionArgs = {
                                tplRef: "sliderCarousel",
                                action: "slickNext"
                              };
                              return (({ tplRef, action, args }) => {
                                return $refs?.[tplRef]?.[action]?.(
                                  ...(args ?? [])
                                );
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["runActionOnSliderCarousel"] != null &&
                          typeof $steps["runActionOnSliderCarousel"] ===
                            "object" &&
                          typeof $steps["runActionOnSliderCarousel"].then ===
                            "function"
                        ) {
                          $steps["runActionOnSliderCarousel"] =
                            await $steps["runActionOnSliderCarousel"];
                        }
                      }}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>
              {(() => {
                const child$Props = {
                  adaptiveHeight: hasVariant(globalVariants, "screen", "large")
                    ? false
                    : true,
                  arrows: false,
                  autoplay: false,
                  autoplaySpeed: hasVariant(globalVariants, "screen", "tablet")
                    ? 4000
                    : 0,
                  beforeChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "currentSlide",
                      ["sliderCarousel", "currentSlide"],
                      SliderWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  centerMode: false,
                  centerPadding: hasVariant(globalVariants, "screen", "mobile")
                    ? "20px"
                    : "50px",
                  className: classNames("__wab_instance", sty.sliderCarousel),
                  cssEase: "linear",
                  dots: hasVariant(globalVariants, "screen", "mobile")
                    ? false
                    : undefined,
                  initialSlide: generateStateValueProp($state, [
                    "sliderCarousel",
                    "currentSlide"
                  ]),
                  pauseOnHover: hasVariant(globalVariants, "screen", "tablet")
                    ? false
                    : undefined,
                  ref: ref => {
                    $refs["sliderCarousel"] = ref;
                  },
                  rows: hasVariant(globalVariants, "screen", "smallLaptop")
                    ? 1
                    : hasVariant(globalVariants, "screen", "smallDesktop")
                      ? 1
                      : 1,
                  sliderScopeClassName: sty["sliderCarousel__slider"],
                  slidesPerRow: hasVariant(globalVariants, "screen", "mobile")
                    ? 1
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? 1
                      : hasVariant(globalVariants, "screen", "smallLaptop")
                        ? 1
                        : hasVariant(globalVariants, "screen", "laptop")
                          ? 2
                          : hasVariant(globalVariants, "screen", "smallDesktop")
                            ? 2
                            : hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mediumDesktop"
                                )
                              ? 2
                              : hasVariant(globalVariants, "screen", "large")
                                ? 3
                                : 1,
                  slidesToShow: hasVariant(
                    globalVariants,
                    "screen",
                    "smallMobile"
                  )
                    ? 1
                    : hasVariant(globalVariants, "screen", "mobile")
                      ? 1
                      : hasVariant(globalVariants, "screen", "tablet")
                        ? 1
                        : hasVariant(globalVariants, "screen", "smallLaptop")
                          ? 1
                          : hasVariant(globalVariants, "screen", "laptop")
                            ? 1
                            : hasVariant(
                                  globalVariants,
                                  "screen",
                                  "smallDesktop"
                                )
                              ? 1
                              : hasVariant(globalVariants, "screen", "large")
                                ? 1
                                : 3,
                  speed: 2000,
                  swipeToSlide: true,
                  variableWidth: hasVariant(globalVariants, "screen", "mobile")
                    ? false
                    : undefined,
                  vertical: hasVariant(globalVariants, "screen", "mobile")
                    ? false
                    : undefined
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "currentSlide",
                      plasmicStateName: "sliderCarousel.currentSlide"
                    }
                  ],
                  [],
                  SliderWrapper_Helpers ?? {},
                  child$Props
                );

                return (
                  <SliderWrapper
                    data-plasmic-name={"sliderCarousel"}
                    data-plasmic-override={overrides.sliderCarousel}
                    {...child$Props}
                  >
                    <div
                      data-plasmic-name={"box"}
                      data-plasmic-override={overrides.box}
                      className={classNames("all", sty.box)}
                    >
                      <div
                        data-plasmic-name={"child"}
                        data-plasmic-override={overrides.child}
                        className={classNames("all", sty.child)}
                      >
                        <div className={classNames("all", sty.freeBox__pYbvD)}>
                          <StarFilledIcon
                            className={classNames("all", sty.svg__ouhzd)}
                            role={"img"}
                          />

                          <StarFilledIcon
                            className={classNames("all", sty.svg__vj58)}
                            role={"img"}
                          />

                          <StarFilledIcon
                            className={classNames("all", sty.svg__kejo)}
                            role={"img"}
                          />

                          <StarFilledIcon
                            className={classNames("all", sty.svg___9Hcpb)}
                            role={"img"}
                          />

                          <StarFilledIcon
                            className={classNames("all", sty.svg__fhrw4)}
                            role={"img"}
                          />
                        </div>
                        <div className={classNames("all", sty.freeBox__bfTeB)}>
                          <div
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.text__cNudu
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a ullamcorper diam, eget consequat neque. Fusce est tellus, vulputate nec commodo ac, dictum non orci. Phasellus pretium, nisl consectetur vestibulum volutpat, mi mauris gravida "
                            }
                          </div>
                        </div>
                        <div className={classNames("all", sty.freeBox__amn6D)}>
                          <div
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.text__gxqVn
                            )}
                          >
                            {"JOHN DOE"}
                          </div>
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__tiW6R)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            format={"avif"}
                            loading={"lazy"}
                            quality={100}
                            src={{
                              src: "/plasmic/sterling_and_buena_vista_foods/images/layer14Png.png",
                              fullWidth: 54,
                              fullHeight: 42,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>
                    </div>
                    {(
                      hasVariant(globalVariants, "screen", "smallDesktop")
                        ? true
                        : hasVariant(globalVariants, "screen", "desktop")
                          ? true
                          : hasVariant(globalVariants, "screen", "large")
                            ? true
                            : false
                    ) ? (
                      <div
                        data-plasmic-name={"box2"}
                        data-plasmic-override={overrides.box2}
                        className={classNames("all", sty.box2)}
                      >
                        <div
                          data-plasmic-name={"child2"}
                          data-plasmic-override={overrides.child2}
                          className={classNames("all", sty.child2)}
                        >
                          <div
                            className={classNames("all", sty.freeBox__bbrPb)}
                          >
                            <StarFilledIcon
                              className={classNames("all", sty.svg__hg2P3)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__wWSe4)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__vHg07)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__dd0Y)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__tMael)}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames("all", sty.freeBox__nVgjj)}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__doP7X
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a ullamcorper diam, eget consequat neque. Fusce est tellus, vulputate nec commodo ac, dictum non orci. Phasellus pretium, nisl consectetur vestibulum volutpat, mi mauris gravida "
                              }
                            </div>
                          </div>
                          <div
                            className={classNames("all", sty.freeBox___3KLw3)}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__fSgfk
                              )}
                            >
                              {"JOHN DOE"}
                            </div>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img___4Knc)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              format={"avif"}
                              loading={"lazy"}
                              quality={100}
                              src={{
                                src: "/plasmic/sterling_and_buena_vista_foods/images/layer14Png.png",
                                fullWidth: 54,
                                fullHeight: 42,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "smallDesktop")
                        ? true
                        : hasVariant(globalVariants, "screen", "desktop")
                          ? true
                          : hasVariant(globalVariants, "screen", "large")
                            ? true
                            : false
                    ) ? (
                      <div
                        data-plasmic-name={"box3"}
                        data-plasmic-override={overrides.box3}
                        className={classNames("all", sty.box3)}
                      >
                        <div
                          data-plasmic-name={"child3"}
                          data-plasmic-override={overrides.child3}
                          className={classNames("all", sty.child3)}
                        >
                          <div
                            className={classNames("all", sty.freeBox__bmB5P)}
                          >
                            <StarFilledIcon
                              className={classNames("all", sty.svg__aKjoU)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg___1BOaP)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__qy22H)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg___8E8HB)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__b1Xkq)}
                              role={"img"}
                            />
                          </div>
                          <div className={classNames("all", sty.freeBox__gAkm)}>
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text___1CI5Y
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a ullamcorper diam, eget consequat neque. Fusce est tellus, vulputate nec commodo ac, dictum non orci. Phasellus pretium, nisl consectetur vestibulum volutpat, mi mauris gravida "
                              }
                            </div>
                          </div>
                          <div
                            className={classNames("all", sty.freeBox__bYxJp)}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__hqd1
                              )}
                            >
                              {"JOHN DOE"}
                            </div>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img___6OO0G)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              format={"avif"}
                              loading={"lazy"}
                              quality={100}
                              src={{
                                src: "/plasmic/sterling_and_buena_vista_foods/images/layer14Png.png",
                                fullWidth: 54,
                                fullHeight: 42,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "smallDesktop")
                        ? true
                        : hasVariant(globalVariants, "screen", "desktop")
                          ? true
                          : hasVariant(globalVariants, "screen", "large")
                            ? true
                            : false
                    ) ? (
                      <div
                        data-plasmic-name={"box4"}
                        data-plasmic-override={overrides.box4}
                        className={classNames("all", sty.box4)}
                      >
                        <div
                          data-plasmic-name={"child4"}
                          data-plasmic-override={overrides.child4}
                          className={classNames("all", sty.child4)}
                        >
                          <div className={classNames("all", sty.freeBox__mnIz)}>
                            <StarFilledIcon
                              className={classNames("all", sty.svg__ueqlD)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__bTdr)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg___0Ix1X)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__wnSyj)}
                              role={"img"}
                            />

                            <StarFilledIcon
                              className={classNames("all", sty.svg__kwhh9)}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames("all", sty.freeBox__nWgsZ)}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__ps6Md
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a ullamcorper diam, eget consequat neque. Fusce est tellus, vulputate nec commodo ac, dictum non orci. Phasellus pretium, nisl consectetur vestibulum volutpat, mi mauris gravida "
                              }
                            </div>
                          </div>
                          <div
                            className={classNames("all", sty.freeBox__bjsfD)}
                          >
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__nqCp4
                              )}
                            >
                              {"JOHN DOE"}
                            </div>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__nQyBb)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              format={"avif"}
                              loading={"lazy"}
                              quality={100}
                              src={{
                                src: "/plasmic/sterling_and_buena_vista_foods/images/layer14Png.png",
                                fullWidth: 54,
                                fullHeight: 42,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    ) : null}
                  </SliderWrapper>
                );
              })()}
            </div>
            <div
              data-plasmic-name={"cta"}
              data-plasmic-override={overrides.cta}
              className={classNames("all", sty.cta)}
            >
              <div className={classNames("all", sty.freeBox__w8Buh)}>
                <div
                  data-plasmic-name={"frame52"}
                  data-plasmic-override={overrides.frame52}
                  className={classNames("all", sty.frame52)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__cQznQ)}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Looking for a "}</React.Fragment>
                      {
                        <span
                          className={classNames(
                            "all",
                            "span",
                            "span__uyaK1",
                            "__wab_text",
                            "plasmic_default__inline",
                            sty.span__yZLq
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "desktop") ? (
                            <React.Fragment>
                              {
                                $queries.wpGraph.data.response.data.pageBy
                                  .pageContent.content[7].headline
                              }
                            </React.Fragment>
                          ) : hasVariant(globalVariants, "screen", "large") ? (
                            <React.Fragment>
                              {
                                $queries.wpGraph.data.response.data.pageBy
                                  .pageContent.content[7].headline
                              }
                            </React.Fragment>
                          ) : (
                            <React.Fragment>
                              {
                                $queries.query.data.response.data.page
                                  .pageContent.content[7].headline
                              }
                            </React.Fragment>
                          )}
                        </span>
                      }
                      <React.Fragment>
                        {" that can grow with you?"}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__uHfOj)}
                >
                  {hasVariant(globalVariants, "screen", "desktop") ? (
                    <React.Fragment>
                      {
                        $queries.wpGraph.data.response.data.pageBy.pageContent
                          .textArea[5].text
                      }
                    </React.Fragment>
                  ) : hasVariant(globalVariants, "screen", "large") ? (
                    <React.Fragment>
                      {
                        $queries.wpGraph.data.response.data.pageBy.pageContent
                          .textArea[5].text
                      }
                    </React.Fragment>
                  ) : (
                    <React.Fragment>
                      {
                        $queries.query.data.response.data.page.pageContent
                          .textArea[5].text
                      }
                    </React.Fragment>
                  )}
                </div>
                <div
                  data-plasmic-name={"buttonContainer"}
                  data-plasmic-override={overrides.buttonContainer}
                  className={classNames("all", sty.buttonContainer)}
                >
                  <PrimaryBtn
                    className={classNames(
                      "__wab_instance",
                      sty.primaryBtn__yeb2D
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.wpGraph.data.response.data.pageBy
                            .pageContent.button[6].text;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Label";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </PrimaryBtn>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"homeFooter"}
            data-plasmic-override={overrides.homeFooter}
            className={classNames("all", sty.homeFooter)}
          >
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  homepage: [
    "homepage",
    "header",
    "homeHero",
    "title",
    "h1",
    "homeBody",
    "intro",
    "text3",
    "title2",
    "section",
    "section2",
    "bakerysolutions",
    "image",
    "text",
    "section3",
    "foodServiceAndRetailPartners",
    "text2",
    "image2",
    "innovationResponsive",
    "buttons",
    "reviews",
    "frame36",
    "frame34",
    "frame35",
    "frame43",
    "frame44",
    "sliderCarousel",
    "box",
    "child",
    "box2",
    "child2",
    "box3",
    "child3",
    "box4",
    "child4",
    "cta",
    "frame52",
    "buttonContainer",
    "homeFooter",
    "footer"
  ],
  header: ["header"],
  homeHero: ["homeHero", "title", "h1"],
  title: ["title", "h1"],
  h1: ["h1"],
  homeBody: [
    "homeBody",
    "intro",
    "text3",
    "title2",
    "section",
    "section2",
    "bakerysolutions",
    "image",
    "text",
    "section3",
    "foodServiceAndRetailPartners",
    "text2",
    "image2",
    "innovationResponsive",
    "buttons",
    "reviews",
    "frame36",
    "frame34",
    "frame35",
    "frame43",
    "frame44",
    "sliderCarousel",
    "box",
    "child",
    "box2",
    "child2",
    "box3",
    "child3",
    "box4",
    "child4",
    "cta",
    "frame52",
    "buttonContainer"
  ],
  intro: ["intro", "text3", "title2"],
  text3: ["text3", "title2"],
  title2: ["title2"],
  section: [
    "section",
    "section2",
    "bakerysolutions",
    "image",
    "text",
    "section3",
    "foodServiceAndRetailPartners",
    "text2",
    "image2"
  ],
  section2: ["section2", "bakerysolutions", "image", "text"],
  bakerysolutions: ["bakerysolutions", "image", "text"],
  image: ["image"],
  text: ["text"],
  section3: ["section3", "foodServiceAndRetailPartners", "text2", "image2"],
  foodServiceAndRetailPartners: [
    "foodServiceAndRetailPartners",
    "text2",
    "image2"
  ],
  text2: ["text2"],
  image2: ["image2"],
  innovationResponsive: ["innovationResponsive", "buttons"],
  buttons: ["buttons"],
  reviews: [
    "reviews",
    "frame36",
    "frame34",
    "frame35",
    "frame43",
    "frame44",
    "sliderCarousel",
    "box",
    "child",
    "box2",
    "child2",
    "box3",
    "child3",
    "box4",
    "child4"
  ],
  frame36: ["frame36", "frame34", "frame35", "frame43", "frame44"],
  frame34: ["frame34"],
  frame35: ["frame35", "frame43", "frame44"],
  frame43: ["frame43"],
  frame44: ["frame44"],
  sliderCarousel: [
    "sliderCarousel",
    "box",
    "child",
    "box2",
    "child2",
    "box3",
    "child3",
    "box4",
    "child4"
  ],
  box: ["box", "child"],
  child: ["child"],
  box2: ["box2", "child2"],
  child2: ["child2"],
  box3: ["box3", "child3"],
  child3: ["child3"],
  box4: ["box4", "child4"],
  child4: ["child4"],
  cta: ["cta", "frame52", "buttonContainer"],
  frame52: ["frame52"],
  buttonContainer: ["buttonContainer"],
  homeFooter: ["homeFooter", "footer"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  homepage: "div";
  header: "div";
  homeHero: "div";
  title: "div";
  h1: "h1";
  homeBody: "div";
  intro: "div";
  text3: "div";
  title2: "div";
  section: "div";
  section2: "div";
  bakerysolutions: "div";
  image: "div";
  text: "div";
  section3: "div";
  foodServiceAndRetailPartners: "div";
  text2: "div";
  image2: "div";
  innovationResponsive: "div";
  buttons: "div";
  reviews: "div";
  frame36: "div";
  frame34: "div";
  frame35: "div";
  frame43: "div";
  frame44: "div";
  sliderCarousel: typeof SliderWrapper;
  box: "div";
  child: "div";
  box2: "div";
  child2: "div";
  box3: "div";
  child3: "div";
  box4: "div";
  child4: "div";
  cta: "div";
  frame52: "div";
  buttonContainer: "div";
  homeFooter: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHome__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "homepage") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("homepage"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    homeHero: makeNodeComponent("homeHero"),
    title: makeNodeComponent("title"),
    h1: makeNodeComponent("h1"),
    homeBody: makeNodeComponent("homeBody"),
    intro: makeNodeComponent("intro"),
    text3: makeNodeComponent("text3"),
    title2: makeNodeComponent("title2"),
    section: makeNodeComponent("section"),
    section2: makeNodeComponent("section2"),
    bakerysolutions: makeNodeComponent("bakerysolutions"),
    image: makeNodeComponent("image"),
    text: makeNodeComponent("text"),
    section3: makeNodeComponent("section3"),
    foodServiceAndRetailPartners: makeNodeComponent(
      "foodServiceAndRetailPartners"
    ),
    text2: makeNodeComponent("text2"),
    image2: makeNodeComponent("image2"),
    innovationResponsive: makeNodeComponent("innovationResponsive"),
    buttons: makeNodeComponent("buttons"),
    reviews: makeNodeComponent("reviews"),
    frame36: makeNodeComponent("frame36"),
    frame34: makeNodeComponent("frame34"),
    frame35: makeNodeComponent("frame35"),
    frame43: makeNodeComponent("frame43"),
    frame44: makeNodeComponent("frame44"),
    sliderCarousel: makeNodeComponent("sliderCarousel"),
    box: makeNodeComponent("box"),
    child: makeNodeComponent("child"),
    box2: makeNodeComponent("box2"),
    child2: makeNodeComponent("child2"),
    box3: makeNodeComponent("box3"),
    child3: makeNodeComponent("child3"),
    box4: makeNodeComponent("box4"),
    child4: makeNodeComponent("child4"),
    cta: makeNodeComponent("cta"),
    frame52: makeNodeComponent("frame52"),
    buttonContainer: makeNodeComponent("buttonContainer"),
    homeFooter: makeNodeComponent("homeFooter"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
