/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fDWv2E51KMppM4Ticmmxiy

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fDWv2E51KMppM4Ticmmxiy/projectModule

const data = {
  base: `${"plasmic_tokens_fDWv2E51KMppM4Ticmmxiy"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
